# mkIndex.tcl --
#
#	This script generates a master pkgIndex.tcl file for tcllib.  It expects 
#	several arguments:
#		outdir		directory in which to create pkgIndex.tcl
#		package		package name (tcllib)
#		version 	package version
#		modules		list of modules to include
#
# Copyright (c) 1999-2000 Ajuba Solutions.
# Copyright (c) 2003      A. Kupries
#
# See the file "license.terms" for information on usage and redistribution
# of this file, and for a DISCLAIMER OF ALL WARRANTIES.
#

proc gen_main_index {outdir package version distribution} {
    set   index [open [file join $outdir pkgIndex.tcl] w]
    puts $index "# Tcl package index file, version 1.1"
    puts $index "# Generated by $package installer for version $version"
    puts $index ""
    puts $index "set maindir \$dir"

    foreach pi [lsort [glob -nocomplain [file join $distribution * pkgIndex.tcl]]] {
	set subdir [file tail [file dirname $pi]]
	puts $index "set dir \[file join \$maindir [list $subdir]\] ;\t source \[file join \$dir pkgIndex.tcl\]"
    }

    puts  $index "unset maindir"
    puts  $index ""
    close $index
    return
}


foreach {outdir package version} $argv {break}
set distribution [file join [file dirname [info script]] modules]

puts __$distribution

gen_main_index $outdir $package $version $distribution
exit
