#!/bin/sh 
# FTP daemon
# \
exec tclsh8.3 "$0" ${1+"$@"}

if {[catch {package require ftpd}]} {
    set here [file dirname [info script]]
    source [file join .. $here ftpd.tcl]
}

proc bgerror {args} {
    global errorInfo
    puts stderr "bgerror: [join $args]"
    puts stderr $errorInfo
}

::ftpd::server
vwait forever
