
As a contributor to Tcllib you are committing yourself to:

[list_begin enumerated]

[enum] Follow the guidelines laid down in
       [term {Tcl Community - Kind Communication}]

[enum] Your contributions getting distributed under a BSD/MIT license.
       For the details see [term {Tcllib - License}]

[list_end]

Contributions are made by entering tickets into our tracker, providing
patches, bundles or branches of code for inclusion, or posting to the
Tcllib related mailing lists.
