[section {Bugs, Ideas, Feedback}]
[vset TRACKER http://core.tcl.tk/tcllib/reportlist]
[vset LABEL   {Tcllib Trackers}]

If you find errors in this document or bugs or problems with the
package it describes, or if you want to suggest improvements for the
documentation or the package, please use the
[uri [vset TRACKER] [vset LABEL]] and specify 
[emph [vset CATEGORY]] as the category.

[para]
When proposing code changes, please provide [emph {unified diffs}],
i.e the output of [const {diff -u}].

[para]
Note further that [emph attachments] are strongly preferred over
inlined patches. Attachments can be made by going to the [const Edit]
form of the ticket immediately after its creation, and then using the
left-most button in the secondary navigation bar.

