###
# This file is automatically generated by the build/build.tcl file
# based on information in the following database:
# http://www.unicode.org/Public/UCD/latest/ucd/EastAsianWidth.txt
#
# (This is the 35th edition, thus version 35 for our package)
###
package provide textutil::wcswidth 35.0
proc ::textutil::wcswidth_type char {
  #  Po         INVERTED EXCLAMATION MARK
  if {$char == 161} { return A }
  #  Sc         CURRENCY SIGN
  if {$char == 164} { return A }
  #  Po         SECTION SIGN
  if {$char == 167} { return A }
  #  Sk         DIAERESIS
  if {$char == 168} { return A }
  #  Lo         FEMININE ORDINAL INDICATOR
  if {$char == 170} { return A }
  #  Cf         SOFT HYPHEN
  if {$char == 173} { return A }
  #  So         REGISTERED SIGN
  if {$char == 174} { return A }
  #  So         DEGREE SIGN
  if {$char == 176} { return A }
  #  Sm         PLUS-MINUS SIGN
  if {$char == 177} { return A }
  #  No     [2] SUPERSCRIPT TWO..SUPERSCRIPT THREE
  if {$char >= 178 && $char <= 179 } { return A }
  #  Sk         ACUTE ACCENT
  if {$char == 180} { return A }
  #  Po     [2] PILCROW SIGN..MIDDLE DOT
  if {$char >= 182 && $char <= 183 } { return A }
  #  Sk         CEDILLA
  if {$char == 184} { return A }
  #  No         SUPERSCRIPT ONE
  if {$char == 185} { return A }
  #  Lo         MASCULINE ORDINAL INDICATOR
  if {$char == 186} { return A }
  #  No     [3] VULGAR FRACTION ONE QUARTER..VULGAR FRACTION THREE QUARTERS
  if {$char >= 188 && $char <= 190 } { return A }
  #  Po         INVERTED QUESTION MARK
  if {$char == 191} { return A }
  #  Lu         LATIN CAPITAL LETTER AE
  if {$char == 198} { return A }
  #  Lu         LATIN CAPITAL LETTER ETH
  if {$char == 208} { return A }
  #  Sm         MULTIPLICATION SIGN
  if {$char == 215} { return A }
  #  Lu         LATIN CAPITAL LETTER O WITH STROKE
  if {$char == 216} { return A }
  #  L&     [4] LATIN CAPITAL LETTER THORN..LATIN SMALL LETTER A WITH ACUTE
  if {$char >= 222 && $char <= 225 } { return A }
  #  Ll         LATIN SMALL LETTER AE
  if {$char == 230} { return A }
  #  Ll     [3] LATIN SMALL LETTER E WITH GRAVE..LATIN SMALL LETTER E WITH CIRCUMFLEX
  if {$char >= 232 && $char <= 234 } { return A }
  #  Ll     [2] LATIN SMALL LETTER I WITH GRAVE..LATIN SMALL LETTER I WITH ACUTE
  if {$char >= 236 && $char <= 237 } { return A }
  #  Ll         LATIN SMALL LETTER ETH
  if {$char == 240} { return A }
  #  Ll     [2] LATIN SMALL LETTER O WITH GRAVE..LATIN SMALL LETTER O WITH ACUTE
  if {$char >= 242 && $char <= 243 } { return A }
  #  Sm         DIVISION SIGN
  if {$char == 247} { return A }
  #  Ll     [3] LATIN SMALL LETTER O WITH STROKE..LATIN SMALL LETTER U WITH ACUTE
  if {$char >= 248 && $char <= 250 } { return A }
  #  Ll         LATIN SMALL LETTER U WITH DIAERESIS
  if {$char == 252} { return A }
  #  Ll         LATIN SMALL LETTER THORN
  if {$char == 254} { return A }
  #  Ll         LATIN SMALL LETTER A WITH MACRON
  if {$char == 257} { return A }
  #  Ll         LATIN SMALL LETTER D WITH STROKE
  if {$char == 273} { return A }
  #  Ll         LATIN SMALL LETTER E WITH MACRON
  if {$char == 275} { return A }
  #  Ll         LATIN SMALL LETTER E WITH CARON
  if {$char == 283} { return A }
  #  L&     [2] LATIN CAPITAL LETTER H WITH STROKE..LATIN SMALL LETTER H WITH STROKE
  if {$char >= 294 && $char <= 295 } { return A }
  #  Ll         LATIN SMALL LETTER I WITH MACRON
  if {$char == 299} { return A }
  #  L&     [3] LATIN SMALL LETTER DOTLESS I..LATIN SMALL LIGATURE IJ
  if {$char >= 305 && $char <= 307 } { return A }
  #  Ll         LATIN SMALL LETTER KRA
  if {$char == 312} { return A }
  #  L&     [4] LATIN CAPITAL LETTER L WITH MIDDLE DOT..LATIN SMALL LETTER L WITH STROKE
  if {$char >= 319 && $char <= 322 } { return A }
  #  Ll         LATIN SMALL LETTER N WITH ACUTE
  if {$char == 324} { return A }
  #  L&     [4] LATIN SMALL LETTER N WITH CARON..LATIN SMALL LETTER ENG
  if {$char >= 328 && $char <= 331 } { return A }
  #  Ll         LATIN SMALL LETTER O WITH MACRON
  if {$char == 333} { return A }
  #  L&     [2] LATIN CAPITAL LIGATURE OE..LATIN SMALL LIGATURE OE
  if {$char >= 338 && $char <= 339 } { return A }
  #  L&     [2] LATIN CAPITAL LETTER T WITH STROKE..LATIN SMALL LETTER T WITH STROKE
  if {$char >= 358 && $char <= 359 } { return A }
  #  Ll         LATIN SMALL LETTER U WITH MACRON
  if {$char == 363} { return A }
  #  Ll         LATIN SMALL LETTER A WITH CARON
  if {$char == 462} { return A }
  #  Ll         LATIN SMALL LETTER I WITH CARON
  if {$char == 464} { return A }
  #  Ll         LATIN SMALL LETTER O WITH CARON
  if {$char == 466} { return A }
  #  Ll         LATIN SMALL LETTER U WITH CARON
  if {$char == 468} { return A }
  #  Ll         LATIN SMALL LETTER U WITH DIAERESIS AND MACRON
  if {$char == 470} { return A }
  #  Ll         LATIN SMALL LETTER U WITH DIAERESIS AND ACUTE
  if {$char == 472} { return A }
  #  Ll         LATIN SMALL LETTER U WITH DIAERESIS AND CARON
  if {$char == 474} { return A }
  #  Ll         LATIN SMALL LETTER U WITH DIAERESIS AND GRAVE
  if {$char == 476} { return A }
  #  Ll         LATIN SMALL LETTER ALPHA
  if {$char == 593} { return A }
  #  Ll         LATIN SMALL LETTER SCRIPT G
  if {$char == 609} { return A }
  #  Sk         MODIFIER LETTER UP ARROWHEAD
  if {$char == 708} { return A }
  #  Lm         CARON
  if {$char == 711} { return A }
  #  Lm     [3] MODIFIER LETTER MACRON..MODIFIER LETTER GRAVE ACCENT
  if {$char >= 713 && $char <= 715 } { return A }
  #  Lm         MODIFIER LETTER LOW MACRON
  if {$char == 717} { return A }
  #  Lm         MODIFIER LETTER TRIANGULAR COLON
  if {$char == 720} { return A }
  #  Sk     [4] BREVE..OGONEK
  if {$char >= 728 && $char <= 731 } { return A }
  #  Sk         DOUBLE ACUTE ACCENT
  if {$char == 733} { return A }
  #  Sk         MODIFIER LETTER CROSS ACCENT
  if {$char == 735} { return A }
  #  Mn   [112] COMBINING GRAVE ACCENT..COMBINING LATIN SMALL LETTER X
  if {$char >= 768 && $char <= 879 } { return A }
  #  Lu    [17] GREEK CAPITAL LETTER ALPHA..GREEK CAPITAL LETTER RHO
  if {$char >= 913 && $char <= 929 } { return A }
  #  Lu     [7] GREEK CAPITAL LETTER SIGMA..GREEK CAPITAL LETTER OMEGA
  if {$char >= 931 && $char <= 937 } { return A }
  #  Ll    [17] GREEK SMALL LETTER ALPHA..GREEK SMALL LETTER RHO
  if {$char >= 945 && $char <= 961 } { return A }
  #  Ll     [7] GREEK SMALL LETTER SIGMA..GREEK SMALL LETTER OMEGA
  if {$char >= 963 && $char <= 969 } { return A }
  #  Lu         CYRILLIC CAPITAL LETTER IO
  if {$char == 1025} { return A }
  #  L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  if {$char >= 1040 && $char <= 1103 } { return A }
  #  Ll         CYRILLIC SMALL LETTER IO
  if {$char == 1105} { return A }
  #  Lo    [96] HANGUL CHOSEONG KIYEOK..HANGUL CHOSEONG FILLER
  if {$char >= 4352 && $char <= 4447 } { return W }
  #  Pd         HYPHEN
  if {$char == 8208} { return A }
  #  Pd     [3] EN DASH..HORIZONTAL BAR
  if {$char >= 8211 && $char <= 8213 } { return A }
  #  Po         DOUBLE VERTICAL LINE
  if {$char == 8214} { return A }
  #  Pi         LEFT SINGLE QUOTATION MARK
  if {$char == 8216} { return A }
  #  Pf         RIGHT SINGLE QUOTATION MARK
  if {$char == 8217} { return A }
  #  Pi         LEFT DOUBLE QUOTATION MARK
  if {$char == 8220} { return A }
  #  Pf         RIGHT DOUBLE QUOTATION MARK
  if {$char == 8221} { return A }
  #  Po     [3] DAGGER..BULLET
  if {$char >= 8224 && $char <= 8226 } { return A }
  #  Po     [4] ONE DOT LEADER..HYPHENATION POINT
  if {$char >= 8228 && $char <= 8231 } { return A }
  #  Po         PER MILLE SIGN
  if {$char == 8240} { return A }
  #  Po     [2] PRIME..DOUBLE PRIME
  if {$char >= 8242 && $char <= 8243 } { return A }
  #  Po         REVERSED PRIME
  if {$char == 8245} { return A }
  #  Po         REFERENCE MARK
  if {$char == 8251} { return A }
  #  Po         OVERLINE
  if {$char == 8254} { return A }
  #  No         SUPERSCRIPT FOUR
  if {$char == 8308} { return A }
  #  Lm         SUPERSCRIPT LATIN SMALL LETTER N
  if {$char == 8319} { return A }
  #  No     [4] SUBSCRIPT ONE..SUBSCRIPT FOUR
  if {$char >= 8321 && $char <= 8324 } { return A }
  #  Sc         WON SIGN
  if {$char == 8361} { return H }
  #  Sc         EURO SIGN
  if {$char == 8364} { return A }
  #  So         DEGREE CELSIUS
  if {$char == 8451} { return A }
  #  So         CARE OF
  if {$char == 8453} { return A }
  #  So         DEGREE FAHRENHEIT
  if {$char == 8457} { return A }
  #  Ll         SCRIPT SMALL L
  if {$char == 8467} { return A }
  #  So         NUMERO SIGN
  if {$char == 8470} { return A }
  #  So     [2] TELEPHONE SIGN..TRADE MARK SIGN
  if {$char >= 8481 && $char <= 8482 } { return A }
  #  Lu         OHM SIGN
  if {$char == 8486} { return A }
  #  Lu         ANGSTROM SIGN
  if {$char == 8491} { return A }
  #  No     [2] VULGAR FRACTION ONE THIRD..VULGAR FRACTION TWO THIRDS
  if {$char >= 8531 && $char <= 8532 } { return A }
  #  No     [4] VULGAR FRACTION ONE EIGHTH..VULGAR FRACTION SEVEN EIGHTHS
  if {$char >= 8539 && $char <= 8542 } { return A }
  #  Nl    [12] ROMAN NUMERAL ONE..ROMAN NUMERAL TWELVE
  if {$char >= 8544 && $char <= 8555 } { return A }
  #  Nl    [10] SMALL ROMAN NUMERAL ONE..SMALL ROMAN NUMERAL TEN
  if {$char >= 8560 && $char <= 8569 } { return A }
  #  No         VULGAR FRACTION ZERO THIRDS
  if {$char == 8585} { return A }
  #  Sm     [5] LEFTWARDS ARROW..LEFT RIGHT ARROW
  if {$char >= 8592 && $char <= 8596 } { return A }
  #  So     [5] UP DOWN ARROW..SOUTH WEST ARROW
  if {$char >= 8597 && $char <= 8601 } { return A }
  #  So     [2] NORTH WEST ARROW TO LONG BAR..LEFTWARDS ARROW TO BAR OVER RIGHTWARDS ARROW TO BAR
  if {$char >= 8632 && $char <= 8633 } { return A }
  #  Sm         RIGHTWARDS DOUBLE ARROW
  if {$char == 8658} { return A }
  #  Sm         LEFT RIGHT DOUBLE ARROW
  if {$char == 8660} { return A }
  #  So         UPWARDS WHITE ARROW
  if {$char == 8679} { return A }
  #  Sm         FOR ALL
  if {$char == 8704} { return A }
  #  Sm     [2] PARTIAL DIFFERENTIAL..THERE EXISTS
  if {$char >= 8706 && $char <= 8707 } { return A }
  #  Sm     [2] NABLA..ELEMENT OF
  if {$char >= 8711 && $char <= 8712 } { return A }
  #  Sm         CONTAINS AS MEMBER
  if {$char == 8715} { return A }
  #  Sm         N-ARY PRODUCT
  if {$char == 8719} { return A }
  #  Sm         N-ARY SUMMATION
  if {$char == 8721} { return A }
  #  Sm         DIVISION SLASH
  if {$char == 8725} { return A }
  #  Sm         SQUARE ROOT
  if {$char == 8730} { return A }
  #  Sm     [4] PROPORTIONAL TO..ANGLE
  if {$char >= 8733 && $char <= 8736 } { return A }
  #  Sm         DIVIDES
  if {$char == 8739} { return A }
  #  Sm         PARALLEL TO
  if {$char == 8741} { return A }
  #  Sm     [6] LOGICAL AND..DOUBLE INTEGRAL
  if {$char >= 8743 && $char <= 8748 } { return A }
  #  Sm         CONTOUR INTEGRAL
  if {$char == 8750} { return A }
  #  Sm     [4] THEREFORE..PROPORTION
  if {$char >= 8756 && $char <= 8759 } { return A }
  #  Sm     [2] TILDE OPERATOR..REVERSED TILDE
  if {$char >= 8764 && $char <= 8765 } { return A }
  #  Sm         ALMOST EQUAL TO
  if {$char == 8776} { return A }
  #  Sm         ALL EQUAL TO
  if {$char == 8780} { return A }
  #  Sm         APPROXIMATELY EQUAL TO OR THE IMAGE OF
  if {$char == 8786} { return A }
  #  Sm     [2] NOT EQUAL TO..IDENTICAL TO
  if {$char >= 8800 && $char <= 8801 } { return A }
  #  Sm     [4] LESS-THAN OR EQUAL TO..GREATER-THAN OVER EQUAL TO
  if {$char >= 8804 && $char <= 8807 } { return A }
  #  Sm     [2] MUCH LESS-THAN..MUCH GREATER-THAN
  if {$char >= 8810 && $char <= 8811 } { return A }
  #  Sm     [2] NOT LESS-THAN..NOT GREATER-THAN
  if {$char >= 8814 && $char <= 8815 } { return A }
  #  Sm     [2] SUBSET OF..SUPERSET OF
  if {$char >= 8834 && $char <= 8835 } { return A }
  #  Sm     [2] SUBSET OF OR EQUAL TO..SUPERSET OF OR EQUAL TO
  if {$char >= 8838 && $char <= 8839 } { return A }
  #  Sm         CIRCLED PLUS
  if {$char == 8853} { return A }
  #  Sm         CIRCLED DOT OPERATOR
  if {$char == 8857} { return A }
  #  Sm         UP TACK
  if {$char == 8869} { return A }
  #  Sm         RIGHT TRIANGLE
  if {$char == 8895} { return A }
  #  So         ARC
  if {$char == 8978} { return A }
  #  So     [2] WATCH..HOURGLASS
  if {$char >= 8986 && $char <= 8987 } { return W }
  #  Ps         LEFT-POINTING ANGLE BRACKET
  if {$char == 9001} { return W }
  #  Pe         RIGHT-POINTING ANGLE BRACKET
  if {$char == 9002} { return W }
  #  So     [4] BLACK RIGHT-POINTING DOUBLE TRIANGLE..BLACK DOWN-POINTING DOUBLE TRIANGLE
  if {$char >= 9193 && $char <= 9196 } { return W }
  #  So         ALARM CLOCK
  if {$char == 9200} { return W }
  #  So         HOURGLASS WITH FLOWING SAND
  if {$char == 9203} { return W }
  #  No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  if {$char >= 9312 && $char <= 9371 } { return A }
  #  So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  if {$char >= 9372 && $char <= 9449 } { return A }
  #  No    [21] NEGATIVE CIRCLED NUMBER ELEVEN..NEGATIVE CIRCLED DIGIT ZERO
  if {$char >= 9451 && $char <= 9471 } { return A }
  #  So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  if {$char >= 9472 && $char <= 9547 } { return A }
  #  So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  if {$char >= 9552 && $char <= 9587 } { return A }
  #  So    [16] UPPER HALF BLOCK..LEFT ONE EIGHTH BLOCK
  if {$char >= 9600 && $char <= 9615 } { return A }
  #  So     [4] MEDIUM SHADE..RIGHT ONE EIGHTH BLOCK
  if {$char >= 9618 && $char <= 9621 } { return A }
  #  So     [2] BLACK SQUARE..WHITE SQUARE
  if {$char >= 9632 && $char <= 9633 } { return A }
  #  So     [7] WHITE SQUARE CONTAINING BLACK SMALL SQUARE..SQUARE WITH DIAGONAL CROSSHATCH FILL
  if {$char >= 9635 && $char <= 9641 } { return A }
  #  So     [2] BLACK UP-POINTING TRIANGLE..WHITE UP-POINTING TRIANGLE
  if {$char >= 9650 && $char <= 9651 } { return A }
  #  So         BLACK RIGHT-POINTING TRIANGLE
  if {$char == 9654} { return A }
  #  Sm         WHITE RIGHT-POINTING TRIANGLE
  if {$char == 9655} { return A }
  #  So     [2] BLACK DOWN-POINTING TRIANGLE..WHITE DOWN-POINTING TRIANGLE
  if {$char >= 9660 && $char <= 9661 } { return A }
  #  So         BLACK LEFT-POINTING TRIANGLE
  if {$char == 9664} { return A }
  #  Sm         WHITE LEFT-POINTING TRIANGLE
  if {$char == 9665} { return A }
  #  So     [3] BLACK DIAMOND..WHITE DIAMOND CONTAINING BLACK SMALL DIAMOND
  if {$char >= 9670 && $char <= 9672 } { return A }
  #  So         WHITE CIRCLE
  if {$char == 9675} { return A }
  #  So     [4] BULLSEYE..CIRCLE WITH RIGHT HALF BLACK
  if {$char >= 9678 && $char <= 9681 } { return A }
  #  So     [4] BLACK LOWER RIGHT TRIANGLE..BLACK UPPER RIGHT TRIANGLE
  if {$char >= 9698 && $char <= 9701 } { return A }
  #  So         LARGE CIRCLE
  if {$char == 9711} { return A }
  #  Sm     [2] WHITE MEDIUM SMALL SQUARE..BLACK MEDIUM SMALL SQUARE
  if {$char >= 9725 && $char <= 9726 } { return W }
  #  So     [2] BLACK STAR..WHITE STAR
  if {$char >= 9733 && $char <= 9734 } { return A }
  #  So         SUN
  if {$char == 9737} { return A }
  #  So     [2] BLACK TELEPHONE..WHITE TELEPHONE
  if {$char >= 9742 && $char <= 9743 } { return A }
  #  So     [2] UMBRELLA WITH RAIN DROPS..HOT BEVERAGE
  if {$char >= 9748 && $char <= 9749 } { return W }
  #  So         WHITE LEFT POINTING INDEX
  if {$char == 9756} { return A }
  #  So         WHITE RIGHT POINTING INDEX
  if {$char == 9758} { return A }
  #  So         FEMALE SIGN
  if {$char == 9792} { return A }
  #  So         MALE SIGN
  if {$char == 9794} { return A }
  #  So    [12] ARIES..PISCES
  if {$char >= 9800 && $char <= 9811 } { return W }
  #  So     [2] BLACK SPADE SUIT..WHITE HEART SUIT
  if {$char >= 9824 && $char <= 9825 } { return A }
  #  So     [3] BLACK CLUB SUIT..BLACK HEART SUIT
  if {$char >= 9827 && $char <= 9829 } { return A }
  #  So     [4] WHITE CLUB SUIT..EIGHTH NOTE
  if {$char >= 9831 && $char <= 9834 } { return A }
  #  So     [2] BEAMED SIXTEENTH NOTES..MUSIC FLAT SIGN
  if {$char >= 9836 && $char <= 9837 } { return A }
  #  Sm         MUSIC SHARP SIGN
  if {$char == 9839} { return A }
  #  So         WHEELCHAIR SYMBOL
  if {$char == 9855} { return W }
  #  So         ANCHOR
  if {$char == 9875} { return W }
  #  So     [2] THREE LINES CONVERGING RIGHT..THREE LINES CONVERGING LEFT
  if {$char >= 9886 && $char <= 9887 } { return A }
  #  So         HIGH VOLTAGE SIGN
  if {$char == 9889} { return W }
  #  So     [2] MEDIUM WHITE CIRCLE..MEDIUM BLACK CIRCLE
  if {$char >= 9898 && $char <= 9899 } { return W }
  #  So     [2] SOCCER BALL..BASEBALL
  if {$char >= 9917 && $char <= 9918 } { return W }
  #  So         SQUARED KEY
  if {$char == 9919} { return A }
  #  So     [2] SNOWMAN WITHOUT SNOW..SUN BEHIND CLOUD
  if {$char >= 9924 && $char <= 9925 } { return W }
  #  So     [8] RAIN..DISABLED CAR
  if {$char >= 9926 && $char <= 9933 } { return A }
  #  So         OPHIUCHUS
  if {$char == 9934} { return W }
  #  So     [5] PICK..CHAINS
  if {$char >= 9935 && $char <= 9939 } { return A }
  #  So         NO ENTRY
  if {$char == 9940} { return W }
  #  So    [13] ALTERNATE ONE-WAY LEFT WAY TRAFFIC..RESTRICTED LEFT ENTRY-2
  if {$char >= 9941 && $char <= 9953 } { return A }
  #  So         HEAVY CIRCLE WITH STROKE AND TWO DOTS ABOVE
  if {$char == 9955} { return A }
  #  So     [2] BLACK CROSS ON SHIELD..SHINTO SHRINE
  if {$char >= 9960 && $char <= 9961 } { return A }
  #  So         CHURCH
  if {$char == 9962} { return W }
  #  So     [7] CASTLE..UMBRELLA ON GROUND
  if {$char >= 9963 && $char <= 9969 } { return A }
  #  So     [2] FOUNTAIN..FLAG IN HOLE
  if {$char >= 9970 && $char <= 9971 } { return W }
  #  So         FERRY
  if {$char == 9972} { return A }
  #  So         SAILBOAT
  if {$char == 9973} { return W }
  #  So     [4] SQUARE FOUR CORNERS..PERSON WITH BALL
  if {$char >= 9974 && $char <= 9977 } { return A }
  #  So         TENT
  if {$char == 9978} { return W }
  #  So     [2] JAPANESE BANK SYMBOL..HEADSTONE GRAVEYARD SYMBOL
  if {$char >= 9979 && $char <= 9980 } { return A }
  #  So         FUEL PUMP
  if {$char == 9981} { return W }
  #  So     [2] CUP ON BLACK SQUARE..WHITE FLAG WITH HORIZONTAL MIDDLE BLACK STRIPE
  if {$char >= 9982 && $char <= 9983 } { return A }
  #  So         WHITE HEAVY CHECK MARK
  if {$char == 9989} { return W }
  #  So     [2] RAISED FIST..RAISED HAND
  if {$char >= 9994 && $char <= 9995 } { return W }
  #  So         SPARKLES
  if {$char == 10024} { return W }
  #  So         HEAVY TEARDROP-SPOKED ASTERISK
  if {$char == 10045} { return A }
  #  So         CROSS MARK
  if {$char == 10060} { return W }
  #  So         NEGATIVE SQUARED CROSS MARK
  if {$char == 10062} { return W }
  #  So     [3] BLACK QUESTION MARK ORNAMENT..WHITE EXCLAMATION MARK ORNAMENT
  if {$char >= 10067 && $char <= 10069 } { return W }
  #  So         HEAVY EXCLAMATION MARK SYMBOL
  if {$char == 10071} { return W }
  #  No    [10] DINGBAT NEGATIVE CIRCLED DIGIT ONE..DINGBAT NEGATIVE CIRCLED NUMBER TEN
  if {$char >= 10102 && $char <= 10111 } { return A }
  #  So     [3] HEAVY PLUS SIGN..HEAVY DIVISION SIGN
  if {$char >= 10133 && $char <= 10135 } { return W }
  #  So         CURLY LOOP
  if {$char == 10160} { return W }
  #  So         DOUBLE CURLY LOOP
  if {$char == 10175} { return W }
  #  So     [2] BLACK LARGE SQUARE..WHITE LARGE SQUARE
  if {$char >= 11035 && $char <= 11036 } { return W }
  #  So         WHITE MEDIUM STAR
  if {$char == 11088} { return W }
  #  So         HEAVY LARGE CIRCLE
  if {$char == 11093} { return W }
  #  So     [4] HEAVY OVAL WITH OVAL INSIDE..HEAVY CIRCLED SALTIRE
  if {$char >= 11094 && $char <= 11097 } { return A }
  #  So    [26] CJK RADICAL REPEAT..CJK RADICAL RAP
  if {$char >= 11904 && $char <= 11929 } { return W }
  #  So    [89] CJK RADICAL CHOKE..CJK RADICAL C-SIMPLIFIED TURTLE
  if {$char >= 11931 && $char <= 12019 } { return W }
  #  So   [214] KANGXI RADICAL ONE..KANGXI RADICAL FLUTE
  if {$char >= 12032 && $char <= 12245 } { return W }
  #  So    [12] IDEOGRAPHIC DESCRIPTION CHARACTER LEFT TO RIGHT..IDEOGRAPHIC DESCRIPTION CHARACTER OVERLAID
  if {$char >= 12272 && $char <= 12283 } { return W }
  #  Zs         IDEOGRAPHIC SPACE
  if {$char == 12288} { return F }
  #  Po     [3] IDEOGRAPHIC COMMA..DITTO MARK
  if {$char >= 12289 && $char <= 12291 } { return W }
  #  So         JAPANESE INDUSTRIAL STANDARD SYMBOL
  if {$char == 12292} { return W }
  #  Lm         IDEOGRAPHIC ITERATION MARK
  if {$char == 12293} { return W }
  #  Lo         IDEOGRAPHIC CLOSING MARK
  if {$char == 12294} { return W }
  #  Nl         IDEOGRAPHIC NUMBER ZERO
  if {$char == 12295} { return W }
  #  Ps         LEFT ANGLE BRACKET
  if {$char == 12296} { return W }
  #  Pe         RIGHT ANGLE BRACKET
  if {$char == 12297} { return W }
  #  Ps         LEFT DOUBLE ANGLE BRACKET
  if {$char == 12298} { return W }
  #  Pe         RIGHT DOUBLE ANGLE BRACKET
  if {$char == 12299} { return W }
  #  Ps         LEFT CORNER BRACKET
  if {$char == 12300} { return W }
  #  Pe         RIGHT CORNER BRACKET
  if {$char == 12301} { return W }
  #  Ps         LEFT WHITE CORNER BRACKET
  if {$char == 12302} { return W }
  #  Pe         RIGHT WHITE CORNER BRACKET
  if {$char == 12303} { return W }
  #  Ps         LEFT BLACK LENTICULAR BRACKET
  if {$char == 12304} { return W }
  #  Pe         RIGHT BLACK LENTICULAR BRACKET
  if {$char == 12305} { return W }
  #  So     [2] POSTAL MARK..GETA MARK
  if {$char >= 12306 && $char <= 12307 } { return W }
  #  Ps         LEFT TORTOISE SHELL BRACKET
  if {$char == 12308} { return W }
  #  Pe         RIGHT TORTOISE SHELL BRACKET
  if {$char == 12309} { return W }
  #  Ps         LEFT WHITE LENTICULAR BRACKET
  if {$char == 12310} { return W }
  #  Pe         RIGHT WHITE LENTICULAR BRACKET
  if {$char == 12311} { return W }
  #  Ps         LEFT WHITE TORTOISE SHELL BRACKET
  if {$char == 12312} { return W }
  #  Pe         RIGHT WHITE TORTOISE SHELL BRACKET
  if {$char == 12313} { return W }
  #  Ps         LEFT WHITE SQUARE BRACKET
  if {$char == 12314} { return W }
  #  Pe         RIGHT WHITE SQUARE BRACKET
  if {$char == 12315} { return W }
  #  Pd         WAVE DASH
  if {$char == 12316} { return W }
  #  Ps         REVERSED DOUBLE PRIME QUOTATION MARK
  if {$char == 12317} { return W }
  #  Pe     [2] DOUBLE PRIME QUOTATION MARK..LOW DOUBLE PRIME QUOTATION MARK
  if {$char >= 12318 && $char <= 12319 } { return W }
  #  So         POSTAL MARK FACE
  if {$char == 12320} { return W }
  #  Nl     [9] HANGZHOU NUMERAL ONE..HANGZHOU NUMERAL NINE
  if {$char >= 12321 && $char <= 12329 } { return W }
  #  Mn     [4] IDEOGRAPHIC LEVEL TONE MARK..IDEOGRAPHIC ENTERING TONE MARK
  if {$char >= 12330 && $char <= 12333 } { return W }
  #  Mc     [2] HANGUL SINGLE DOT TONE MARK..HANGUL DOUBLE DOT TONE MARK
  if {$char >= 12334 && $char <= 12335 } { return W }
  #  Pd         WAVY DASH
  if {$char == 12336} { return W }
  #  Lm     [5] VERTICAL KANA REPEAT MARK..VERTICAL KANA REPEAT MARK LOWER HALF
  if {$char >= 12337 && $char <= 12341 } { return W }
  #  So     [2] CIRCLED POSTAL MARK..IDEOGRAPHIC TELEGRAPH LINE FEED SEPARATOR SYMBOL
  if {$char >= 12342 && $char <= 12343 } { return W }
  #  Nl     [3] HANGZHOU NUMERAL TEN..HANGZHOU NUMERAL THIRTY
  if {$char >= 12344 && $char <= 12346 } { return W }
  #  Lm         VERTICAL IDEOGRAPHIC ITERATION MARK
  if {$char == 12347} { return W }
  #  Lo         MASU MARK
  if {$char == 12348} { return W }
  #  Po         PART ALTERNATION MARK
  if {$char == 12349} { return W }
  #  So         IDEOGRAPHIC VARIATION INDICATOR
  if {$char == 12350} { return W }
  #  Lo    [86] HIRAGANA LETTER SMALL A..HIRAGANA LETTER SMALL KE
  if {$char >= 12353 && $char <= 12438 } { return W }
  #  Mn     [2] COMBINING KATAKANA-HIRAGANA VOICED SOUND MARK..COMBINING KATAKANA-HIRAGANA SEMI-VOICED SOUND MARK
  if {$char >= 12441 && $char <= 12442 } { return W }
  #  Sk     [2] KATAKANA-HIRAGANA VOICED SOUND MARK..KATAKANA-HIRAGANA SEMI-VOICED SOUND MARK
  if {$char >= 12443 && $char <= 12444 } { return W }
  #  Lm     [2] HIRAGANA ITERATION MARK..HIRAGANA VOICED ITERATION MARK
  if {$char >= 12445 && $char <= 12446 } { return W }
  #  Lo         HIRAGANA DIGRAPH YORI
  if {$char == 12447} { return W }
  #  Pd         KATAKANA-HIRAGANA DOUBLE HYPHEN
  if {$char == 12448} { return W }
  #  Lo    [90] KATAKANA LETTER SMALL A..KATAKANA LETTER VO
  if {$char >= 12449 && $char <= 12538 } { return W }
  #  Po         KATAKANA MIDDLE DOT
  if {$char == 12539} { return W }
  #  Lm     [3] KATAKANA-HIRAGANA PROLONGED SOUND MARK..KATAKANA VOICED ITERATION MARK
  if {$char >= 12540 && $char <= 12542 } { return W }
  #  Lo         KATAKANA DIGRAPH KOTO
  if {$char == 12543} { return W }
  #  Lo    [43] BOPOMOFO LETTER B..BOPOMOFO LETTER NN
  if {$char >= 12549 && $char <= 12591 } { return W }
  #  Lo    [94] HANGUL LETTER KIYEOK..HANGUL LETTER ARAEAE
  if {$char >= 12593 && $char <= 12686 } { return W }
  #  So     [2] IDEOGRAPHIC ANNOTATION LINKING MARK..IDEOGRAPHIC ANNOTATION REVERSE MARK
  if {$char >= 12688 && $char <= 12689 } { return W }
  #  No     [4] IDEOGRAPHIC ANNOTATION ONE MARK..IDEOGRAPHIC ANNOTATION FOUR MARK
  if {$char >= 12690 && $char <= 12693 } { return W }
  #  So    [10] IDEOGRAPHIC ANNOTATION TOP MARK..IDEOGRAPHIC ANNOTATION MAN MARK
  if {$char >= 12694 && $char <= 12703 } { return W }
  #  Lo    [27] BOPOMOFO LETTER BU..BOPOMOFO LETTER ZY
  if {$char >= 12704 && $char <= 12730 } { return W }
  #  So    [36] CJK STROKE T..CJK STROKE Q
  if {$char >= 12736 && $char <= 12771 } { return W }
  #  Lo    [16] KATAKANA LETTER SMALL KU..KATAKANA LETTER SMALL RO
  if {$char >= 12784 && $char <= 12799 } { return W }
  #  So    [31] PARENTHESIZED HANGUL KIYEOK..PARENTHESIZED KOREAN CHARACTER O HU
  if {$char >= 12800 && $char <= 12830 } { return W }
  #  No    [10] PARENTHESIZED IDEOGRAPH ONE..PARENTHESIZED IDEOGRAPH TEN
  if {$char >= 12832 && $char <= 12841 } { return W }
  #  So    [30] PARENTHESIZED IDEOGRAPH MOON..CIRCLED IDEOGRAPH KOTO
  if {$char >= 12842 && $char <= 12871 } { return W }
  #  No     [8] CIRCLED NUMBER TEN ON BLACK SQUARE..CIRCLED NUMBER EIGHTY ON BLACK SQUARE
  if {$char >= 12872 && $char <= 12879 } { return A }
  #  So         PARTNERSHIP SIGN
  if {$char == 12880} { return W }
  #  No    [15] CIRCLED NUMBER TWENTY ONE..CIRCLED NUMBER THIRTY FIVE
  if {$char >= 12881 && $char <= 12895 } { return W }
  #  So    [32] CIRCLED HANGUL KIYEOK..KOREAN STANDARD SYMBOL
  if {$char >= 12896 && $char <= 12927 } { return W }
  #  No    [10] CIRCLED IDEOGRAPH ONE..CIRCLED IDEOGRAPH TEN
  if {$char >= 12928 && $char <= 12937 } { return W }
  #  So    [39] CIRCLED IDEOGRAPH MOON..CIRCLED IDEOGRAPH NIGHT
  if {$char >= 12938 && $char <= 12976 } { return W }
  #  No    [15] CIRCLED NUMBER THIRTY SIX..CIRCLED NUMBER FIFTY
  if {$char >= 12977 && $char <= 12991 } { return W }
  #  So    [63] IDEOGRAPHIC TELEGRAPH SYMBOL FOR JANUARY..CIRCLED KATAKANA WO
  if {$char >= 12992 && $char <= 13054 } { return W }
  #  So   [256] SQUARE APAATO..SQUARE GAL
  if {$char >= 13056 && $char <= 13311 } { return W }
  #  Lo  [6582] CJK UNIFIED IDEOGRAPH-3400..CJK UNIFIED IDEOGRAPH-4DB5
  if {$char >= 13312 && $char <= 19893 } { return W }
  #  Cn    [10] <reserved-4DB6>..<reserved-4DBF>
  if {$char >= 19894 && $char <= 19903 } { return W }
  #  Lo [20976] CJK UNIFIED IDEOGRAPH-4E00..CJK UNIFIED IDEOGRAPH-9FEF
  if {$char >= 19968 && $char <= 40943 } { return W }
  #  Cn    [16] <reserved-9FF0>..<reserved-9FFF>
  if {$char >= 40944 && $char <= 40959 } { return W }
  #  Lo    [21] YI SYLLABLE IT..YI SYLLABLE E
  if {$char >= 40960 && $char <= 40980 } { return W }
  #  Lm         YI SYLLABLE WU
  if {$char == 40981} { return W }
  #  Lo  [1143] YI SYLLABLE BIT..YI SYLLABLE YYR
  if {$char >= 40982 && $char <= 42124 } { return W }
  #  So    [55] YI RADICAL QOT..YI RADICAL KE
  if {$char >= 42128 && $char <= 42182 } { return W }
  #  Lo    [29] HANGUL CHOSEONG TIKEUT-MIEUM..HANGUL CHOSEONG SSANGYEORINHIEUH
  if {$char >= 43360 && $char <= 43388 } { return W }
  #  Lo [11172] HANGUL SYLLABLE GA..HANGUL SYLLABLE HIH
  if {$char >= 44032 && $char <= 55203 } { return W }
  #  Co  [6400] <private-use-E000>..<private-use-F8FF>
  if {$char >= 57344 && $char <= 63743 } { return A }
  #  Lo   [366] CJK COMPATIBILITY IDEOGRAPH-F900..CJK COMPATIBILITY IDEOGRAPH-FA6D
  if {$char >= 63744 && $char <= 64109 } { return W }
  #  Cn     [2] <reserved-FA6E>..<reserved-FA6F>
  if {$char >= 64110 && $char <= 64111 } { return W }
  #  Lo   [106] CJK COMPATIBILITY IDEOGRAPH-FA70..CJK COMPATIBILITY IDEOGRAPH-FAD9
  if {$char >= 64112 && $char <= 64217 } { return W }
  #  Cn    [38] <reserved-FADA>..<reserved-FAFF>
  if {$char >= 64218 && $char <= 64255 } { return W }
  #  Mn    [16] VARIATION SELECTOR-1..VARIATION SELECTOR-16
  if {$char >= 65024 && $char <= 65039 } { return A }
  #  Po     [7] PRESENTATION FORM FOR VERTICAL COMMA..PRESENTATION FORM FOR VERTICAL QUESTION MARK
  if {$char >= 65040 && $char <= 65046 } { return W }
  #  Ps         PRESENTATION FORM FOR VERTICAL LEFT WHITE LENTICULAR BRACKET
  if {$char == 65047} { return W }
  #  Pe         PRESENTATION FORM FOR VERTICAL RIGHT WHITE LENTICULAR BRAKCET
  if {$char == 65048} { return W }
  #  Po         PRESENTATION FORM FOR VERTICAL HORIZONTAL ELLIPSIS
  if {$char == 65049} { return W }
  #  Po         PRESENTATION FORM FOR VERTICAL TWO DOT LEADER
  if {$char == 65072} { return W }
  #  Pd     [2] PRESENTATION FORM FOR VERTICAL EM DASH..PRESENTATION FORM FOR VERTICAL EN DASH
  if {$char >= 65073 && $char <= 65074 } { return W }
  #  Pc     [2] PRESENTATION FORM FOR VERTICAL LOW LINE..PRESENTATION FORM FOR VERTICAL WAVY LOW LINE
  if {$char >= 65075 && $char <= 65076 } { return W }
  #  Ps         PRESENTATION FORM FOR VERTICAL LEFT PARENTHESIS
  if {$char == 65077} { return W }
  #  Pe         PRESENTATION FORM FOR VERTICAL RIGHT PARENTHESIS
  if {$char == 65078} { return W }
  #  Ps         PRESENTATION FORM FOR VERTICAL LEFT CURLY BRACKET
  if {$char == 65079} { return W }
  #  Pe         PRESENTATION FORM FOR VERTICAL RIGHT CURLY BRACKET
  if {$char == 65080} { return W }
  #  Ps         PRESENTATION FORM FOR VERTICAL LEFT TORTOISE SHELL BRACKET
  if {$char == 65081} { return W }
  #  Pe         PRESENTATION FORM FOR VERTICAL RIGHT TORTOISE SHELL BRACKET
  if {$char == 65082} { return W }
  #  Ps         PRESENTATION FORM FOR VERTICAL LEFT BLACK LENTICULAR BRACKET
  if {$char == 65083} { return W }
  #  Pe         PRESENTATION FORM FOR VERTICAL RIGHT BLACK LENTICULAR BRACKET
  if {$char == 65084} { return W }
  #  Ps         PRESENTATION FORM FOR VERTICAL LEFT DOUBLE ANGLE BRACKET
  if {$char == 65085} { return W }
  #  Pe         PRESENTATION FORM FOR VERTICAL RIGHT DOUBLE ANGLE BRACKET
  if {$char == 65086} { return W }
  #  Ps         PRESENTATION FORM FOR VERTICAL LEFT ANGLE BRACKET
  if {$char == 65087} { return W }
  #  Pe         PRESENTATION FORM FOR VERTICAL RIGHT ANGLE BRACKET
  if {$char == 65088} { return W }
  #  Ps         PRESENTATION FORM FOR VERTICAL LEFT CORNER BRACKET
  if {$char == 65089} { return W }
  #  Pe         PRESENTATION FORM FOR VERTICAL RIGHT CORNER BRACKET
  if {$char == 65090} { return W }
  #  Ps         PRESENTATION FORM FOR VERTICAL LEFT WHITE CORNER BRACKET
  if {$char == 65091} { return W }
  #  Pe         PRESENTATION FORM FOR VERTICAL RIGHT WHITE CORNER BRACKET
  if {$char == 65092} { return W }
  #  Po     [2] SESAME DOT..WHITE SESAME DOT
  if {$char >= 65093 && $char <= 65094 } { return W }
  #  Ps         PRESENTATION FORM FOR VERTICAL LEFT SQUARE BRACKET
  if {$char == 65095} { return W }
  #  Pe         PRESENTATION FORM FOR VERTICAL RIGHT SQUARE BRACKET
  if {$char == 65096} { return W }
  #  Po     [4] DASHED OVERLINE..DOUBLE WAVY OVERLINE
  if {$char >= 65097 && $char <= 65100 } { return W }
  #  Pc     [3] DASHED LOW LINE..WAVY LOW LINE
  if {$char >= 65101 && $char <= 65103 } { return W }
  #  Po     [3] SMALL COMMA..SMALL FULL STOP
  if {$char >= 65104 && $char <= 65106 } { return W }
  #  Po     [4] SMALL SEMICOLON..SMALL EXCLAMATION MARK
  if {$char >= 65108 && $char <= 65111 } { return W }
  #  Pd         SMALL EM DASH
  if {$char == 65112} { return W }
  #  Ps         SMALL LEFT PARENTHESIS
  if {$char == 65113} { return W }
  #  Pe         SMALL RIGHT PARENTHESIS
  if {$char == 65114} { return W }
  #  Ps         SMALL LEFT CURLY BRACKET
  if {$char == 65115} { return W }
  #  Pe         SMALL RIGHT CURLY BRACKET
  if {$char == 65116} { return W }
  #  Ps         SMALL LEFT TORTOISE SHELL BRACKET
  if {$char == 65117} { return W }
  #  Pe         SMALL RIGHT TORTOISE SHELL BRACKET
  if {$char == 65118} { return W }
  #  Po     [3] SMALL NUMBER SIGN..SMALL ASTERISK
  if {$char >= 65119 && $char <= 65121 } { return W }
  #  Sm         SMALL PLUS SIGN
  if {$char == 65122} { return W }
  #  Pd         SMALL HYPHEN-MINUS
  if {$char == 65123} { return W }
  #  Sm     [3] SMALL LESS-THAN SIGN..SMALL EQUALS SIGN
  if {$char >= 65124 && $char <= 65126 } { return W }
  #  Po         SMALL REVERSE SOLIDUS
  if {$char == 65128} { return W }
  #  Sc         SMALL DOLLAR SIGN
  if {$char == 65129} { return W }
  #  Po     [2] SMALL PERCENT SIGN..SMALL COMMERCIAL AT
  if {$char >= 65130 && $char <= 65131 } { return W }
  #  Po     [3] FULLWIDTH EXCLAMATION MARK..FULLWIDTH NUMBER SIGN
  if {$char >= 65281 && $char <= 65283 } { return F }
  #  Sc         FULLWIDTH DOLLAR SIGN
  if {$char == 65284} { return F }
  #  Po     [3] FULLWIDTH PERCENT SIGN..FULLWIDTH APOSTROPHE
  if {$char >= 65285 && $char <= 65287 } { return F }
  #  Ps         FULLWIDTH LEFT PARENTHESIS
  if {$char == 65288} { return F }
  #  Pe         FULLWIDTH RIGHT PARENTHESIS
  if {$char == 65289} { return F }
  #  Po         FULLWIDTH ASTERISK
  if {$char == 65290} { return F }
  #  Sm         FULLWIDTH PLUS SIGN
  if {$char == 65291} { return F }
  #  Po         FULLWIDTH COMMA
  if {$char == 65292} { return F }
  #  Pd         FULLWIDTH HYPHEN-MINUS
  if {$char == 65293} { return F }
  #  Po     [2] FULLWIDTH FULL STOP..FULLWIDTH SOLIDUS
  if {$char >= 65294 && $char <= 65295 } { return F }
  #  Nd    [10] FULLWIDTH DIGIT ZERO..FULLWIDTH DIGIT NINE
  if {$char >= 65296 && $char <= 65305 } { return F }
  #  Po     [2] FULLWIDTH COLON..FULLWIDTH SEMICOLON
  if {$char >= 65306 && $char <= 65307 } { return F }
  #  Sm     [3] FULLWIDTH LESS-THAN SIGN..FULLWIDTH GREATER-THAN SIGN
  if {$char >= 65308 && $char <= 65310 } { return F }
  #  Po     [2] FULLWIDTH QUESTION MARK..FULLWIDTH COMMERCIAL AT
  if {$char >= 65311 && $char <= 65312 } { return F }
  #  Lu    [26] FULLWIDTH LATIN CAPITAL LETTER A..FULLWIDTH LATIN CAPITAL LETTER Z
  if {$char >= 65313 && $char <= 65338 } { return F }
  #  Ps         FULLWIDTH LEFT SQUARE BRACKET
  if {$char == 65339} { return F }
  #  Po         FULLWIDTH REVERSE SOLIDUS
  if {$char == 65340} { return F }
  #  Pe         FULLWIDTH RIGHT SQUARE BRACKET
  if {$char == 65341} { return F }
  #  Sk         FULLWIDTH CIRCUMFLEX ACCENT
  if {$char == 65342} { return F }
  #  Pc         FULLWIDTH LOW LINE
  if {$char == 65343} { return F }
  #  Sk         FULLWIDTH GRAVE ACCENT
  if {$char == 65344} { return F }
  #  Ll    [26] FULLWIDTH LATIN SMALL LETTER A..FULLWIDTH LATIN SMALL LETTER Z
  if {$char >= 65345 && $char <= 65370 } { return F }
  #  Ps         FULLWIDTH LEFT CURLY BRACKET
  if {$char == 65371} { return F }
  #  Sm         FULLWIDTH VERTICAL LINE
  if {$char == 65372} { return F }
  #  Pe         FULLWIDTH RIGHT CURLY BRACKET
  if {$char == 65373} { return F }
  #  Sm         FULLWIDTH TILDE
  if {$char == 65374} { return F }
  #  Ps         FULLWIDTH LEFT WHITE PARENTHESIS
  if {$char == 65375} { return F }
  #  Pe         FULLWIDTH RIGHT WHITE PARENTHESIS
  if {$char == 65376} { return F }
  #  Po         HALFWIDTH IDEOGRAPHIC FULL STOP
  if {$char == 65377} { return H }
  #  Ps         HALFWIDTH LEFT CORNER BRACKET
  if {$char == 65378} { return H }
  #  Pe         HALFWIDTH RIGHT CORNER BRACKET
  if {$char == 65379} { return H }
  #  Po     [2] HALFWIDTH IDEOGRAPHIC COMMA..HALFWIDTH KATAKANA MIDDLE DOT
  if {$char >= 65380 && $char <= 65381 } { return H }
  #  Lo    [10] HALFWIDTH KATAKANA LETTER WO..HALFWIDTH KATAKANA LETTER SMALL TU
  if {$char >= 65382 && $char <= 65391 } { return H }
  #  Lm         HALFWIDTH KATAKANA-HIRAGANA PROLONGED SOUND MARK
  if {$char == 65392} { return H }
  #  Lo    [45] HALFWIDTH KATAKANA LETTER A..HALFWIDTH KATAKANA LETTER N
  if {$char >= 65393 && $char <= 65437 } { return H }
  #  Lm     [2] HALFWIDTH KATAKANA VOICED SOUND MARK..HALFWIDTH KATAKANA SEMI-VOICED SOUND MARK
  if {$char >= 65438 && $char <= 65439 } { return H }
  #  Lo    [31] HALFWIDTH HANGUL FILLER..HALFWIDTH HANGUL LETTER HIEUH
  if {$char >= 65440 && $char <= 65470 } { return H }
  #  Lo     [6] HALFWIDTH HANGUL LETTER A..HALFWIDTH HANGUL LETTER E
  if {$char >= 65474 && $char <= 65479 } { return H }
  #  Lo     [6] HALFWIDTH HANGUL LETTER YEO..HALFWIDTH HANGUL LETTER OE
  if {$char >= 65482 && $char <= 65487 } { return H }
  #  Lo     [6] HALFWIDTH HANGUL LETTER YO..HALFWIDTH HANGUL LETTER YU
  if {$char >= 65490 && $char <= 65495 } { return H }
  #  Lo     [3] HALFWIDTH HANGUL LETTER EU..HALFWIDTH HANGUL LETTER I
  if {$char >= 65498 && $char <= 65500 } { return H }
  #  Sc     [2] FULLWIDTH CENT SIGN..FULLWIDTH POUND SIGN
  if {$char >= 65504 && $char <= 65505 } { return F }
  #  Sm         FULLWIDTH NOT SIGN
  if {$char == 65506} { return F }
  #  Sk         FULLWIDTH MACRON
  if {$char == 65507} { return F }
  #  So         FULLWIDTH BROKEN BAR
  if {$char == 65508} { return F }
  #  Sc     [2] FULLWIDTH YEN SIGN..FULLWIDTH WON SIGN
  if {$char >= 65509 && $char <= 65510 } { return F }
  #  So         HALFWIDTH FORMS LIGHT VERTICAL
  if {$char == 65512} { return H }
  #  Sm     [4] HALFWIDTH LEFTWARDS ARROW..HALFWIDTH DOWNWARDS ARROW
  if {$char >= 65513 && $char <= 65516 } { return H }
  #  So     [2] HALFWIDTH BLACK SQUARE..HALFWIDTH WHITE CIRCLE
  if {$char >= 65517 && $char <= 65518 } { return H }
  #  So         REPLACEMENT CHARACTER
  if {$char == 65533} { return A }
  #  Lm     [2] TANGUT ITERATION MARK..NUSHU ITERATION MARK
  if {$char >= 94176 && $char <= 94177 } { return W }
  #  Lo  [6130] TANGUT IDEOGRAPH-17000..TANGUT IDEOGRAPH-187F1
  if {$char >= 94208 && $char <= 100337 } { return W }
  #  Lo   [755] TANGUT COMPONENT-001..TANGUT COMPONENT-755
  if {$char >= 100352 && $char <= 101106 } { return W }
  #  Lo   [256] KATAKANA LETTER ARCHAIC E..HENTAIGANA LETTER RE-2
  if {$char >= 110592 && $char <= 110847 } { return W }
  #  Lo    [31] HENTAIGANA LETTER RE-3..HENTAIGANA LETTER N-MU-MO-2
  if {$char >= 110848 && $char <= 110878 } { return W }
  #  Lo   [396] NUSHU CHARACTER-1B170..NUSHU CHARACTER-1B2FB
  if {$char >= 110960 && $char <= 111355 } { return W }
  #  So         MAHJONG TILE RED DRAGON
  if {$char == 126980} { return W }
  #  So         PLAYING CARD BLACK JOKER
  if {$char == 127183} { return W }
  #  No    [11] DIGIT ZERO FULL STOP..DIGIT NINE COMMA
  if {$char >= 127232 && $char <= 127242 } { return A }
  #  So    [30] PARENTHESIZED LATIN CAPITAL LETTER A..CIRCLED CD
  if {$char >= 127248 && $char <= 127277 } { return A }
  #  So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  if {$char >= 127280 && $char <= 127337 } { return A }
  #  So    [30] NEGATIVE SQUARED LATIN CAPITAL LETTER A..NEGATIVE SQUARED SA
  if {$char >= 127344 && $char <= 127373 } { return A }
  #  So         NEGATIVE SQUARED AB
  if {$char == 127374} { return W }
  #  So     [2] NEGATIVE SQUARED WC..SQUARE DJ
  if {$char >= 127375 && $char <= 127376 } { return A }
  #  So    [10] SQUARED CL..SQUARED VS
  if {$char >= 127377 && $char <= 127386 } { return W }
  #  So    [18] SQUARED THREE D..SQUARED VOD
  if {$char >= 127387 && $char <= 127404 } { return A }
  #  So     [3] SQUARE HIRAGANA HOKA..SQUARED KATAKANA SA
  if {$char >= 127488 && $char <= 127490 } { return W }
  #  So    [44] SQUARED CJK UNIFIED IDEOGRAPH-624B..SQUARED CJK UNIFIED IDEOGRAPH-914D
  if {$char >= 127504 && $char <= 127547 } { return W }
  #  So     [9] TORTOISE SHELL BRACKETED CJK UNIFIED IDEOGRAPH-672C..TORTOISE SHELL BRACKETED CJK UNIFIED IDEOGRAPH-6557
  if {$char >= 127552 && $char <= 127560 } { return W }
  #  So     [2] CIRCLED IDEOGRAPH ADVANTAGE..CIRCLED IDEOGRAPH ACCEPT
  if {$char >= 127568 && $char <= 127569 } { return W }
  #  So     [6] ROUNDED SYMBOL FOR FU..ROUNDED SYMBOL FOR CAI
  if {$char >= 127584 && $char <= 127589 } { return W }
  #  So    [33] CYCLONE..SHOOTING STAR
  if {$char >= 127744 && $char <= 127776 } { return W }
  #  So     [9] HOT DOG..CACTUS
  if {$char >= 127789 && $char <= 127797 } { return W }
  #  So    [70] TULIP..BABY BOTTLE
  if {$char >= 127799 && $char <= 127868 } { return W }
  #  So    [22] BOTTLE WITH POPPING CORK..GRADUATION CAP
  if {$char >= 127870 && $char <= 127891 } { return W }
  #  So    [43] CAROUSEL HORSE..SWIMMER
  if {$char >= 127904 && $char <= 127946 } { return W }
  #  So     [5] CRICKET BAT AND BALL..TABLE TENNIS PADDLE AND BALL
  if {$char >= 127951 && $char <= 127955 } { return W }
  #  So    [17] HOUSE BUILDING..EUROPEAN CASTLE
  if {$char >= 127968 && $char <= 127984 } { return W }
  #  So         WAVING BLACK FLAG
  if {$char == 127988} { return W }
  #  So     [3] BADMINTON RACQUET AND SHUTTLECOCK..AMPHORA
  if {$char >= 127992 && $char <= 127994 } { return W }
  #  Sk     [5] EMOJI MODIFIER FITZPATRICK TYPE-1-2..EMOJI MODIFIER FITZPATRICK TYPE-6
  if {$char >= 127995 && $char <= 127999 } { return W }
  #  So    [63] RAT..PAW PRINTS
  if {$char >= 128000 && $char <= 128062 } { return W }
  #  So         EYES
  if {$char == 128064} { return W }
  #  So   [187] EAR..VIDEOCASSETTE
  if {$char >= 128066 && $char <= 128252 } { return W }
  #  So    [63] PRAYER BEADS..DOWN-POINTING SMALL RED TRIANGLE
  if {$char >= 128255 && $char <= 128317 } { return W }
  #  So     [4] KAABA..MENORAH WITH NINE BRANCHES
  if {$char >= 128331 && $char <= 128334 } { return W }
  #  So    [24] CLOCK FACE ONE OCLOCK..CLOCK FACE TWELVE-THIRTY
  if {$char >= 128336 && $char <= 128359 } { return W }
  #  So         MAN DANCING
  if {$char == 128378} { return W }
  #  So     [2] REVERSED HAND WITH MIDDLE FINGER EXTENDED..RAISED HAND WITH PART BETWEEN MIDDLE AND RING FINGERS
  if {$char >= 128405 && $char <= 128406 } { return W }
  #  So         BLACK HEART
  if {$char == 128420} { return W }
  #  So     [5] MOUNT FUJI..MOYAI
  if {$char >= 128507 && $char <= 128511 } { return W }
  #  So    [80] GRINNING FACE..PERSON WITH FOLDED HANDS
  if {$char >= 128512 && $char <= 128591 } { return W }
  #  So    [70] ROCKET..LEFT LUGGAGE
  if {$char >= 128640 && $char <= 128709 } { return W }
  #  So         SLEEPING ACCOMMODATION
  if {$char == 128716} { return W }
  #  So     [3] PLACE OF WORSHIP..SHOPPING TROLLEY
  if {$char >= 128720 && $char <= 128722 } { return W }
  #  So     [2] AIRPLANE DEPARTURE..AIRPLANE ARRIVING
  if {$char >= 128747 && $char <= 128748 } { return W }
  #  So     [6] SCOOTER..SKATEBOARD
  if {$char >= 128756 && $char <= 128761 } { return W }
  #  So    [47] ZIPPER-MOUTH FACE..HANDBALL
  if {$char >= 129296 && $char <= 129342 } { return W }
  #  So    [49] WILTED FLOWER..SMILING FACE WITH SMILING EYES AND THREE HEARTS
  if {$char >= 129344 && $char <= 129392 } { return W }
  #  So     [4] FACE WITH PARTY HORN AND PARTY HAT..FREEZING FACE
  if {$char >= 129395 && $char <= 129398 } { return W }
  #  So         FACE WITH PLEADING EYES
  if {$char == 129402} { return W }
  #  So    [39] LAB COAT..SWAN
  if {$char >= 129404 && $char <= 129442 } { return W }
  #  So    [10] EMOJI COMPONENT RED HAIR..SUPERVILLAIN
  if {$char >= 129456 && $char <= 129465 } { return W }
  #  So     [3] CHEESE WEDGE..SALT SHAKER
  if {$char >= 129472 && $char <= 129474 } { return W }
  #  So    [48] FACE WITH MONOCLE..NAZAR AMULET
  if {$char >= 129488 && $char <= 129535 } { return W }
  #  Lo [42711] CJK UNIFIED IDEOGRAPH-20000..CJK UNIFIED IDEOGRAPH-2A6D6
  if {$char >= 131072 && $char <= 173782 } { return W }
  #  Cn    [41] <reserved-2A6D7>..<reserved-2A6FF>
  if {$char >= 173783 && $char <= 173823 } { return W }
  #  Lo  [4149] CJK UNIFIED IDEOGRAPH-2A700..CJK UNIFIED IDEOGRAPH-2B734
  if {$char >= 173824 && $char <= 177972 } { return W }
  #  Cn    [11] <reserved-2B735>..<reserved-2B73F>
  if {$char >= 177973 && $char <= 177983 } { return W }
  #  Lo   [222] CJK UNIFIED IDEOGRAPH-2B740..CJK UNIFIED IDEOGRAPH-2B81D
  if {$char >= 177984 && $char <= 178205 } { return W }
  #  Cn     [2] <reserved-2B81E>..<reserved-2B81F>
  if {$char >= 178206 && $char <= 178207 } { return W }
  #  Lo  [5762] CJK UNIFIED IDEOGRAPH-2B820..CJK UNIFIED IDEOGRAPH-2CEA1
  if {$char >= 178208 && $char <= 183969 } { return W }
  #  Cn    [14] <reserved-2CEA2>..<reserved-2CEAF>
  if {$char >= 183970 && $char <= 183983 } { return W }
  #  Lo  [7473] CJK UNIFIED IDEOGRAPH-2CEB0..CJK UNIFIED IDEOGRAPH-2EBE0
  if {$char >= 183984 && $char <= 191456 } { return W }
  #  Cn  [3103] <reserved-2EBE1>..<reserved-2F7FF>
  if {$char >= 191457 && $char <= 194559 } { return W }
  #  Lo   [542] CJK COMPATIBILITY IDEOGRAPH-2F800..CJK COMPATIBILITY IDEOGRAPH-2FA1D
  if {$char >= 194560 && $char <= 195101 } { return W }
  #  Cn     [2] <reserved-2FA1E>..<reserved-2FA1F>
  if {$char >= 195102 && $char <= 195103 } { return W }
  #  Cn  [1502] <reserved-2FA20>..<reserved-2FFFD>
  if {$char >= 195104 && $char <= 196605 } { return W }
  #  Cn [65534] <reserved-30000>..<reserved-3FFFD>
  if {$char >= 196608 && $char <= 262141 } { return W }
  #  Mn   [240] VARIATION SELECTOR-17..VARIATION SELECTOR-256
  if {$char >= 917760 && $char <= 917999 } { return A }
  #  Co [65534] <private-use-F0000>..<private-use-FFFFD>
  if {$char >= 983040 && $char <= 1048573 } { return A }
  #  Co [65534] <private-use-100000>..<private-use-10FFFD>
  if {$char >= 1048576 && $char <= 1114109 } { return A }
  return N
}
proc ::textutil::wcswidth_char char {
  #  Lo    [96] HANGUL CHOSEONG KIYEOK..HANGUL CHOSEONG FILLER
  if {$char >= 4352 && $char <= 4447 } { return 2 }
  #  So     [2] WATCH..HOURGLASS
  if {$char >= 8986 && $char <= 8987 } { return 2 }
  #  Ps         LEFT-POINTING ANGLE BRACKET
  if {$char == 9001} { return 2 }
  #  Pe         RIGHT-POINTING ANGLE BRACKET
  if {$char == 9002} { return 2 }
  #  So     [4] BLACK RIGHT-POINTING DOUBLE TRIANGLE..BLACK DOWN-POINTING DOUBLE TRIANGLE
  if {$char >= 9193 && $char <= 9196 } { return 2 }
  #  So         ALARM CLOCK
  if {$char == 9200} { return 2 }
  #  So         HOURGLASS WITH FLOWING SAND
  if {$char == 9203} { return 2 }
  #  Sm     [2] WHITE MEDIUM SMALL SQUARE..BLACK MEDIUM SMALL SQUARE
  if {$char >= 9725 && $char <= 9726 } { return 2 }
  #  So     [2] UMBRELLA WITH RAIN DROPS..HOT BEVERAGE
  if {$char >= 9748 && $char <= 9749 } { return 2 }
  #  So    [12] ARIES..PISCES
  if {$char >= 9800 && $char <= 9811 } { return 2 }
  #  So         WHEELCHAIR SYMBOL
  if {$char == 9855} { return 2 }
  #  So         ANCHOR
  if {$char == 9875} { return 2 }
  #  So         HIGH VOLTAGE SIGN
  if {$char == 9889} { return 2 }
  #  So     [2] MEDIUM WHITE CIRCLE..MEDIUM BLACK CIRCLE
  if {$char >= 9898 && $char <= 9899 } { return 2 }
  #  So     [2] SOCCER BALL..BASEBALL
  if {$char >= 9917 && $char <= 9918 } { return 2 }
  #  So     [2] SNOWMAN WITHOUT SNOW..SUN BEHIND CLOUD
  if {$char >= 9924 && $char <= 9925 } { return 2 }
  #  So         OPHIUCHUS
  if {$char == 9934} { return 2 }
  #  So         NO ENTRY
  if {$char == 9940} { return 2 }
  #  So         CHURCH
  if {$char == 9962} { return 2 }
  #  So     [2] FOUNTAIN..FLAG IN HOLE
  if {$char >= 9970 && $char <= 9971 } { return 2 }
  #  So         SAILBOAT
  if {$char == 9973} { return 2 }
  #  So         TENT
  if {$char == 9978} { return 2 }
  #  So         FUEL PUMP
  if {$char == 9981} { return 2 }
  #  So         WHITE HEAVY CHECK MARK
  if {$char == 9989} { return 2 }
  #  So     [2] RAISED FIST..RAISED HAND
  if {$char >= 9994 && $char <= 9995 } { return 2 }
  #  So         SPARKLES
  if {$char == 10024} { return 2 }
  #  So         CROSS MARK
  if {$char == 10060} { return 2 }
  #  So         NEGATIVE SQUARED CROSS MARK
  if {$char == 10062} { return 2 }
  #  So     [3] BLACK QUESTION MARK ORNAMENT..WHITE EXCLAMATION MARK ORNAMENT
  if {$char >= 10067 && $char <= 10069 } { return 2 }
  #  So         HEAVY EXCLAMATION MARK SYMBOL
  if {$char == 10071} { return 2 }
  #  So     [3] HEAVY PLUS SIGN..HEAVY DIVISION SIGN
  if {$char >= 10133 && $char <= 10135 } { return 2 }
  #  So         CURLY LOOP
  if {$char == 10160} { return 2 }
  #  So         DOUBLE CURLY LOOP
  if {$char == 10175} { return 2 }
  #  So     [2] BLACK LARGE SQUARE..WHITE LARGE SQUARE
  if {$char >= 11035 && $char <= 11036 } { return 2 }
  #  So         WHITE MEDIUM STAR
  if {$char == 11088} { return 2 }
  #  So         HEAVY LARGE CIRCLE
  if {$char == 11093} { return 2 }
  #  So    [26] CJK RADICAL REPEAT..CJK RADICAL RAP
  if {$char >= 11904 && $char <= 11929 } { return 2 }
  #  So    [89] CJK RADICAL CHOKE..CJK RADICAL C-SIMPLIFIED TURTLE
  if {$char >= 11931 && $char <= 12019 } { return 2 }
  #  So   [214] KANGXI RADICAL ONE..KANGXI RADICAL FLUTE
  if {$char >= 12032 && $char <= 12245 } { return 2 }
  #  So    [12] IDEOGRAPHIC DESCRIPTION CHARACTER LEFT TO RIGHT..IDEOGRAPHIC DESCRIPTION CHARACTER OVERLAID
  if {$char >= 12272 && $char <= 12283 } { return 2 }
  #  Zs         IDEOGRAPHIC SPACE
  if {$char == 12288} { return 2 }
  #  Po     [3] IDEOGRAPHIC COMMA..DITTO MARK
  if {$char >= 12289 && $char <= 12291 } { return 2 }
  #  So         JAPANESE INDUSTRIAL STANDARD SYMBOL
  if {$char == 12292} { return 2 }
  #  Lm         IDEOGRAPHIC ITERATION MARK
  if {$char == 12293} { return 2 }
  #  Lo         IDEOGRAPHIC CLOSING MARK
  if {$char == 12294} { return 2 }
  #  Nl         IDEOGRAPHIC NUMBER ZERO
  if {$char == 12295} { return 2 }
  #  Ps         LEFT ANGLE BRACKET
  if {$char == 12296} { return 2 }
  #  Pe         RIGHT ANGLE BRACKET
  if {$char == 12297} { return 2 }
  #  Ps         LEFT DOUBLE ANGLE BRACKET
  if {$char == 12298} { return 2 }
  #  Pe         RIGHT DOUBLE ANGLE BRACKET
  if {$char == 12299} { return 2 }
  #  Ps         LEFT CORNER BRACKET
  if {$char == 12300} { return 2 }
  #  Pe         RIGHT CORNER BRACKET
  if {$char == 12301} { return 2 }
  #  Ps         LEFT WHITE CORNER BRACKET
  if {$char == 12302} { return 2 }
  #  Pe         RIGHT WHITE CORNER BRACKET
  if {$char == 12303} { return 2 }
  #  Ps         LEFT BLACK LENTICULAR BRACKET
  if {$char == 12304} { return 2 }
  #  Pe         RIGHT BLACK LENTICULAR BRACKET
  if {$char == 12305} { return 2 }
  #  So     [2] POSTAL MARK..GETA MARK
  if {$char >= 12306 && $char <= 12307 } { return 2 }
  #  Ps         LEFT TORTOISE SHELL BRACKET
  if {$char == 12308} { return 2 }
  #  Pe         RIGHT TORTOISE SHELL BRACKET
  if {$char == 12309} { return 2 }
  #  Ps         LEFT WHITE LENTICULAR BRACKET
  if {$char == 12310} { return 2 }
  #  Pe         RIGHT WHITE LENTICULAR BRACKET
  if {$char == 12311} { return 2 }
  #  Ps         LEFT WHITE TORTOISE SHELL BRACKET
  if {$char == 12312} { return 2 }
  #  Pe         RIGHT WHITE TORTOISE SHELL BRACKET
  if {$char == 12313} { return 2 }
  #  Ps         LEFT WHITE SQUARE BRACKET
  if {$char == 12314} { return 2 }
  #  Pe         RIGHT WHITE SQUARE BRACKET
  if {$char == 12315} { return 2 }
  #  Pd         WAVE DASH
  if {$char == 12316} { return 2 }
  #  Ps         REVERSED DOUBLE PRIME QUOTATION MARK
  if {$char == 12317} { return 2 }
  #  Pe     [2] DOUBLE PRIME QUOTATION MARK..LOW DOUBLE PRIME QUOTATION MARK
  if {$char >= 12318 && $char <= 12319 } { return 2 }
  #  So         POSTAL MARK FACE
  if {$char == 12320} { return 2 }
  #  Nl     [9] HANGZHOU NUMERAL ONE..HANGZHOU NUMERAL NINE
  if {$char >= 12321 && $char <= 12329 } { return 2 }
  #  Mn     [4] IDEOGRAPHIC LEVEL TONE MARK..IDEOGRAPHIC ENTERING TONE MARK
  if {$char >= 12330 && $char <= 12333 } { return 2 }
  #  Mc     [2] HANGUL SINGLE DOT TONE MARK..HANGUL DOUBLE DOT TONE MARK
  if {$char >= 12334 && $char <= 12335 } { return 2 }
  #  Pd         WAVY DASH
  if {$char == 12336} { return 2 }
  #  Lm     [5] VERTICAL KANA REPEAT MARK..VERTICAL KANA REPEAT MARK LOWER HALF
  if {$char >= 12337 && $char <= 12341 } { return 2 }
  #  So     [2] CIRCLED POSTAL MARK..IDEOGRAPHIC TELEGRAPH LINE FEED SEPARATOR SYMBOL
  if {$char >= 12342 && $char <= 12343 } { return 2 }
  #  Nl     [3] HANGZHOU NUMERAL TEN..HANGZHOU NUMERAL THIRTY
  if {$char >= 12344 && $char <= 12346 } { return 2 }
  #  Lm         VERTICAL IDEOGRAPHIC ITERATION MARK
  if {$char == 12347} { return 2 }
  #  Lo         MASU MARK
  if {$char == 12348} { return 2 }
  #  Po         PART ALTERNATION MARK
  if {$char == 12349} { return 2 }
  #  So         IDEOGRAPHIC VARIATION INDICATOR
  if {$char == 12350} { return 2 }
  #  Lo    [86] HIRAGANA LETTER SMALL A..HIRAGANA LETTER SMALL KE
  if {$char >= 12353 && $char <= 12438 } { return 2 }
  #  Mn     [2] COMBINING KATAKANA-HIRAGANA VOICED SOUND MARK..COMBINING KATAKANA-HIRAGANA SEMI-VOICED SOUND MARK
  if {$char >= 12441 && $char <= 12442 } { return 2 }
  #  Sk     [2] KATAKANA-HIRAGANA VOICED SOUND MARK..KATAKANA-HIRAGANA SEMI-VOICED SOUND MARK
  if {$char >= 12443 && $char <= 12444 } { return 2 }
  #  Lm     [2] HIRAGANA ITERATION MARK..HIRAGANA VOICED ITERATION MARK
  if {$char >= 12445 && $char <= 12446 } { return 2 }
  #  Lo         HIRAGANA DIGRAPH YORI
  if {$char == 12447} { return 2 }
  #  Pd         KATAKANA-HIRAGANA DOUBLE HYPHEN
  if {$char == 12448} { return 2 }
  #  Lo    [90] KATAKANA LETTER SMALL A..KATAKANA LETTER VO
  if {$char >= 12449 && $char <= 12538 } { return 2 }
  #  Po         KATAKANA MIDDLE DOT
  if {$char == 12539} { return 2 }
  #  Lm     [3] KATAKANA-HIRAGANA PROLONGED SOUND MARK..KATAKANA VOICED ITERATION MARK
  if {$char >= 12540 && $char <= 12542 } { return 2 }
  #  Lo         KATAKANA DIGRAPH KOTO
  if {$char == 12543} { return 2 }
  #  Lo    [43] BOPOMOFO LETTER B..BOPOMOFO LETTER NN
  if {$char >= 12549 && $char <= 12591 } { return 2 }
  #  Lo    [94] HANGUL LETTER KIYEOK..HANGUL LETTER ARAEAE
  if {$char >= 12593 && $char <= 12686 } { return 2 }
  #  So     [2] IDEOGRAPHIC ANNOTATION LINKING MARK..IDEOGRAPHIC ANNOTATION REVERSE MARK
  if {$char >= 12688 && $char <= 12689 } { return 2 }
  #  No     [4] IDEOGRAPHIC ANNOTATION ONE MARK..IDEOGRAPHIC ANNOTATION FOUR MARK
  if {$char >= 12690 && $char <= 12693 } { return 2 }
  #  So    [10] IDEOGRAPHIC ANNOTATION TOP MARK..IDEOGRAPHIC ANNOTATION MAN MARK
  if {$char >= 12694 && $char <= 12703 } { return 2 }
  #  Lo    [27] BOPOMOFO LETTER BU..BOPOMOFO LETTER ZY
  if {$char >= 12704 && $char <= 12730 } { return 2 }
  #  So    [36] CJK STROKE T..CJK STROKE Q
  if {$char >= 12736 && $char <= 12771 } { return 2 }
  #  Lo    [16] KATAKANA LETTER SMALL KU..KATAKANA LETTER SMALL RO
  if {$char >= 12784 && $char <= 12799 } { return 2 }
  #  So    [31] PARENTHESIZED HANGUL KIYEOK..PARENTHESIZED KOREAN CHARACTER O HU
  if {$char >= 12800 && $char <= 12830 } { return 2 }
  #  No    [10] PARENTHESIZED IDEOGRAPH ONE..PARENTHESIZED IDEOGRAPH TEN
  if {$char >= 12832 && $char <= 12841 } { return 2 }
  #  So    [30] PARENTHESIZED IDEOGRAPH MOON..CIRCLED IDEOGRAPH KOTO
  if {$char >= 12842 && $char <= 12871 } { return 2 }
  #  So         PARTNERSHIP SIGN
  if {$char == 12880} { return 2 }
  #  No    [15] CIRCLED NUMBER TWENTY ONE..CIRCLED NUMBER THIRTY FIVE
  if {$char >= 12881 && $char <= 12895 } { return 2 }
  #  So    [32] CIRCLED HANGUL KIYEOK..KOREAN STANDARD SYMBOL
  if {$char >= 12896 && $char <= 12927 } { return 2 }
  #  No    [10] CIRCLED IDEOGRAPH ONE..CIRCLED IDEOGRAPH TEN
  if {$char >= 12928 && $char <= 12937 } { return 2 }
  #  So    [39] CIRCLED IDEOGRAPH MOON..CIRCLED IDEOGRAPH NIGHT
  if {$char >= 12938 && $char <= 12976 } { return 2 }
  #  No    [15] CIRCLED NUMBER THIRTY SIX..CIRCLED NUMBER FIFTY
  if {$char >= 12977 && $char <= 12991 } { return 2 }
  #  So    [63] IDEOGRAPHIC TELEGRAPH SYMBOL FOR JANUARY..CIRCLED KATAKANA WO
  if {$char >= 12992 && $char <= 13054 } { return 2 }
  #  So   [256] SQUARE APAATO..SQUARE GAL
  if {$char >= 13056 && $char <= 13311 } { return 2 }
  #  Lo  [6582] CJK UNIFIED IDEOGRAPH-3400..CJK UNIFIED IDEOGRAPH-4DB5
  if {$char >= 13312 && $char <= 19893 } { return 2 }
  #  Cn    [10] <reserved-4DB6>..<reserved-4DBF>
  if {$char >= 19894 && $char <= 19903 } { return 2 }
  #  Lo [20976] CJK UNIFIED IDEOGRAPH-4E00..CJK UNIFIED IDEOGRAPH-9FEF
  if {$char >= 19968 && $char <= 40943 } { return 2 }
  #  Cn    [16] <reserved-9FF0>..<reserved-9FFF>
  if {$char >= 40944 && $char <= 40959 } { return 2 }
  #  Lo    [21] YI SYLLABLE IT..YI SYLLABLE E
  if {$char >= 40960 && $char <= 40980 } { return 2 }
  #  Lm         YI SYLLABLE WU
  if {$char == 40981} { return 2 }
  #  Lo  [1143] YI SYLLABLE BIT..YI SYLLABLE YYR
  if {$char >= 40982 && $char <= 42124 } { return 2 }
  #  So    [55] YI RADICAL QOT..YI RADICAL KE
  if {$char >= 42128 && $char <= 42182 } { return 2 }
  #  Lo    [29] HANGUL CHOSEONG TIKEUT-MIEUM..HANGUL CHOSEONG SSANGYEORINHIEUH
  if {$char >= 43360 && $char <= 43388 } { return 2 }
  #  Lo [11172] HANGUL SYLLABLE GA..HANGUL SYLLABLE HIH
  if {$char >= 44032 && $char <= 55203 } { return 2 }
  #  Lo   [366] CJK COMPATIBILITY IDEOGRAPH-F900..CJK COMPATIBILITY IDEOGRAPH-FA6D
  if {$char >= 63744 && $char <= 64109 } { return 2 }
  #  Cn     [2] <reserved-FA6E>..<reserved-FA6F>
  if {$char >= 64110 && $char <= 64111 } { return 2 }
  #  Lo   [106] CJK COMPATIBILITY IDEOGRAPH-FA70..CJK COMPATIBILITY IDEOGRAPH-FAD9
  if {$char >= 64112 && $char <= 64217 } { return 2 }
  #  Cn    [38] <reserved-FADA>..<reserved-FAFF>
  if {$char >= 64218 && $char <= 64255 } { return 2 }
  #  Po     [7] PRESENTATION FORM FOR VERTICAL COMMA..PRESENTATION FORM FOR VERTICAL QUESTION MARK
  if {$char >= 65040 && $char <= 65046 } { return 2 }
  #  Ps         PRESENTATION FORM FOR VERTICAL LEFT WHITE LENTICULAR BRACKET
  if {$char == 65047} { return 2 }
  #  Pe         PRESENTATION FORM FOR VERTICAL RIGHT WHITE LENTICULAR BRAKCET
  if {$char == 65048} { return 2 }
  #  Po         PRESENTATION FORM FOR VERTICAL HORIZONTAL ELLIPSIS
  if {$char == 65049} { return 2 }
  #  Po         PRESENTATION FORM FOR VERTICAL TWO DOT LEADER
  if {$char == 65072} { return 2 }
  #  Pd     [2] PRESENTATION FORM FOR VERTICAL EM DASH..PRESENTATION FORM FOR VERTICAL EN DASH
  if {$char >= 65073 && $char <= 65074 } { return 2 }
  #  Pc     [2] PRESENTATION FORM FOR VERTICAL LOW LINE..PRESENTATION FORM FOR VERTICAL WAVY LOW LINE
  if {$char >= 65075 && $char <= 65076 } { return 2 }
  #  Ps         PRESENTATION FORM FOR VERTICAL LEFT PARENTHESIS
  if {$char == 65077} { return 2 }
  #  Pe         PRESENTATION FORM FOR VERTICAL RIGHT PARENTHESIS
  if {$char == 65078} { return 2 }
  #  Ps         PRESENTATION FORM FOR VERTICAL LEFT CURLY BRACKET
  if {$char == 65079} { return 2 }
  #  Pe         PRESENTATION FORM FOR VERTICAL RIGHT CURLY BRACKET
  if {$char == 65080} { return 2 }
  #  Ps         PRESENTATION FORM FOR VERTICAL LEFT TORTOISE SHELL BRACKET
  if {$char == 65081} { return 2 }
  #  Pe         PRESENTATION FORM FOR VERTICAL RIGHT TORTOISE SHELL BRACKET
  if {$char == 65082} { return 2 }
  #  Ps         PRESENTATION FORM FOR VERTICAL LEFT BLACK LENTICULAR BRACKET
  if {$char == 65083} { return 2 }
  #  Pe         PRESENTATION FORM FOR VERTICAL RIGHT BLACK LENTICULAR BRACKET
  if {$char == 65084} { return 2 }
  #  Ps         PRESENTATION FORM FOR VERTICAL LEFT DOUBLE ANGLE BRACKET
  if {$char == 65085} { return 2 }
  #  Pe         PRESENTATION FORM FOR VERTICAL RIGHT DOUBLE ANGLE BRACKET
  if {$char == 65086} { return 2 }
  #  Ps         PRESENTATION FORM FOR VERTICAL LEFT ANGLE BRACKET
  if {$char == 65087} { return 2 }
  #  Pe         PRESENTATION FORM FOR VERTICAL RIGHT ANGLE BRACKET
  if {$char == 65088} { return 2 }
  #  Ps         PRESENTATION FORM FOR VERTICAL LEFT CORNER BRACKET
  if {$char == 65089} { return 2 }
  #  Pe         PRESENTATION FORM FOR VERTICAL RIGHT CORNER BRACKET
  if {$char == 65090} { return 2 }
  #  Ps         PRESENTATION FORM FOR VERTICAL LEFT WHITE CORNER BRACKET
  if {$char == 65091} { return 2 }
  #  Pe         PRESENTATION FORM FOR VERTICAL RIGHT WHITE CORNER BRACKET
  if {$char == 65092} { return 2 }
  #  Po     [2] SESAME DOT..WHITE SESAME DOT
  if {$char >= 65093 && $char <= 65094 } { return 2 }
  #  Ps         PRESENTATION FORM FOR VERTICAL LEFT SQUARE BRACKET
  if {$char == 65095} { return 2 }
  #  Pe         PRESENTATION FORM FOR VERTICAL RIGHT SQUARE BRACKET
  if {$char == 65096} { return 2 }
  #  Po     [4] DASHED OVERLINE..DOUBLE WAVY OVERLINE
  if {$char >= 65097 && $char <= 65100 } { return 2 }
  #  Pc     [3] DASHED LOW LINE..WAVY LOW LINE
  if {$char >= 65101 && $char <= 65103 } { return 2 }
  #  Po     [3] SMALL COMMA..SMALL FULL STOP
  if {$char >= 65104 && $char <= 65106 } { return 2 }
  #  Po     [4] SMALL SEMICOLON..SMALL EXCLAMATION MARK
  if {$char >= 65108 && $char <= 65111 } { return 2 }
  #  Pd         SMALL EM DASH
  if {$char == 65112} { return 2 }
  #  Ps         SMALL LEFT PARENTHESIS
  if {$char == 65113} { return 2 }
  #  Pe         SMALL RIGHT PARENTHESIS
  if {$char == 65114} { return 2 }
  #  Ps         SMALL LEFT CURLY BRACKET
  if {$char == 65115} { return 2 }
  #  Pe         SMALL RIGHT CURLY BRACKET
  if {$char == 65116} { return 2 }
  #  Ps         SMALL LEFT TORTOISE SHELL BRACKET
  if {$char == 65117} { return 2 }
  #  Pe         SMALL RIGHT TORTOISE SHELL BRACKET
  if {$char == 65118} { return 2 }
  #  Po     [3] SMALL NUMBER SIGN..SMALL ASTERISK
  if {$char >= 65119 && $char <= 65121 } { return 2 }
  #  Sm         SMALL PLUS SIGN
  if {$char == 65122} { return 2 }
  #  Pd         SMALL HYPHEN-MINUS
  if {$char == 65123} { return 2 }
  #  Sm     [3] SMALL LESS-THAN SIGN..SMALL EQUALS SIGN
  if {$char >= 65124 && $char <= 65126 } { return 2 }
  #  Po         SMALL REVERSE SOLIDUS
  if {$char == 65128} { return 2 }
  #  Sc         SMALL DOLLAR SIGN
  if {$char == 65129} { return 2 }
  #  Po     [2] SMALL PERCENT SIGN..SMALL COMMERCIAL AT
  if {$char >= 65130 && $char <= 65131 } { return 2 }
  #  Po     [3] FULLWIDTH EXCLAMATION MARK..FULLWIDTH NUMBER SIGN
  if {$char >= 65281 && $char <= 65283 } { return 2 }
  #  Sc         FULLWIDTH DOLLAR SIGN
  if {$char == 65284} { return 2 }
  #  Po     [3] FULLWIDTH PERCENT SIGN..FULLWIDTH APOSTROPHE
  if {$char >= 65285 && $char <= 65287 } { return 2 }
  #  Ps         FULLWIDTH LEFT PARENTHESIS
  if {$char == 65288} { return 2 }
  #  Pe         FULLWIDTH RIGHT PARENTHESIS
  if {$char == 65289} { return 2 }
  #  Po         FULLWIDTH ASTERISK
  if {$char == 65290} { return 2 }
  #  Sm         FULLWIDTH PLUS SIGN
  if {$char == 65291} { return 2 }
  #  Po         FULLWIDTH COMMA
  if {$char == 65292} { return 2 }
  #  Pd         FULLWIDTH HYPHEN-MINUS
  if {$char == 65293} { return 2 }
  #  Po     [2] FULLWIDTH FULL STOP..FULLWIDTH SOLIDUS
  if {$char >= 65294 && $char <= 65295 } { return 2 }
  #  Nd    [10] FULLWIDTH DIGIT ZERO..FULLWIDTH DIGIT NINE
  if {$char >= 65296 && $char <= 65305 } { return 2 }
  #  Po     [2] FULLWIDTH COLON..FULLWIDTH SEMICOLON
  if {$char >= 65306 && $char <= 65307 } { return 2 }
  #  Sm     [3] FULLWIDTH LESS-THAN SIGN..FULLWIDTH GREATER-THAN SIGN
  if {$char >= 65308 && $char <= 65310 } { return 2 }
  #  Po     [2] FULLWIDTH QUESTION MARK..FULLWIDTH COMMERCIAL AT
  if {$char >= 65311 && $char <= 65312 } { return 2 }
  #  Lu    [26] FULLWIDTH LATIN CAPITAL LETTER A..FULLWIDTH LATIN CAPITAL LETTER Z
  if {$char >= 65313 && $char <= 65338 } { return 2 }
  #  Ps         FULLWIDTH LEFT SQUARE BRACKET
  if {$char == 65339} { return 2 }
  #  Po         FULLWIDTH REVERSE SOLIDUS
  if {$char == 65340} { return 2 }
  #  Pe         FULLWIDTH RIGHT SQUARE BRACKET
  if {$char == 65341} { return 2 }
  #  Sk         FULLWIDTH CIRCUMFLEX ACCENT
  if {$char == 65342} { return 2 }
  #  Pc         FULLWIDTH LOW LINE
  if {$char == 65343} { return 2 }
  #  Sk         FULLWIDTH GRAVE ACCENT
  if {$char == 65344} { return 2 }
  #  Ll    [26] FULLWIDTH LATIN SMALL LETTER A..FULLWIDTH LATIN SMALL LETTER Z
  if {$char >= 65345 && $char <= 65370 } { return 2 }
  #  Ps         FULLWIDTH LEFT CURLY BRACKET
  if {$char == 65371} { return 2 }
  #  Sm         FULLWIDTH VERTICAL LINE
  if {$char == 65372} { return 2 }
  #  Pe         FULLWIDTH RIGHT CURLY BRACKET
  if {$char == 65373} { return 2 }
  #  Sm         FULLWIDTH TILDE
  if {$char == 65374} { return 2 }
  #  Ps         FULLWIDTH LEFT WHITE PARENTHESIS
  if {$char == 65375} { return 2 }
  #  Pe         FULLWIDTH RIGHT WHITE PARENTHESIS
  if {$char == 65376} { return 2 }
  #  Sc     [2] FULLWIDTH CENT SIGN..FULLWIDTH POUND SIGN
  if {$char >= 65504 && $char <= 65505 } { return 2 }
  #  Sm         FULLWIDTH NOT SIGN
  if {$char == 65506} { return 2 }
  #  Sk         FULLWIDTH MACRON
  if {$char == 65507} { return 2 }
  #  So         FULLWIDTH BROKEN BAR
  if {$char == 65508} { return 2 }
  #  Sc     [2] FULLWIDTH YEN SIGN..FULLWIDTH WON SIGN
  if {$char >= 65509 && $char <= 65510 } { return 2 }
  #  Lm     [2] TANGUT ITERATION MARK..NUSHU ITERATION MARK
  if {$char >= 94176 && $char <= 94177 } { return 2 }
  #  Lo  [6130] TANGUT IDEOGRAPH-17000..TANGUT IDEOGRAPH-187F1
  if {$char >= 94208 && $char <= 100337 } { return 2 }
  #  Lo   [755] TANGUT COMPONENT-001..TANGUT COMPONENT-755
  if {$char >= 100352 && $char <= 101106 } { return 2 }
  #  Lo   [256] KATAKANA LETTER ARCHAIC E..HENTAIGANA LETTER RE-2
  if {$char >= 110592 && $char <= 110847 } { return 2 }
  #  Lo    [31] HENTAIGANA LETTER RE-3..HENTAIGANA LETTER N-MU-MO-2
  if {$char >= 110848 && $char <= 110878 } { return 2 }
  #  Lo   [396] NUSHU CHARACTER-1B170..NUSHU CHARACTER-1B2FB
  if {$char >= 110960 && $char <= 111355 } { return 2 }
  #  So         MAHJONG TILE RED DRAGON
  if {$char == 126980} { return 2 }
  #  So         PLAYING CARD BLACK JOKER
  if {$char == 127183} { return 2 }
  #  So         NEGATIVE SQUARED AB
  if {$char == 127374} { return 2 }
  #  So    [10] SQUARED CL..SQUARED VS
  if {$char >= 127377 && $char <= 127386 } { return 2 }
  #  So     [3] SQUARE HIRAGANA HOKA..SQUARED KATAKANA SA
  if {$char >= 127488 && $char <= 127490 } { return 2 }
  #  So    [44] SQUARED CJK UNIFIED IDEOGRAPH-624B..SQUARED CJK UNIFIED IDEOGRAPH-914D
  if {$char >= 127504 && $char <= 127547 } { return 2 }
  #  So     [9] TORTOISE SHELL BRACKETED CJK UNIFIED IDEOGRAPH-672C..TORTOISE SHELL BRACKETED CJK UNIFIED IDEOGRAPH-6557
  if {$char >= 127552 && $char <= 127560 } { return 2 }
  #  So     [2] CIRCLED IDEOGRAPH ADVANTAGE..CIRCLED IDEOGRAPH ACCEPT
  if {$char >= 127568 && $char <= 127569 } { return 2 }
  #  So     [6] ROUNDED SYMBOL FOR FU..ROUNDED SYMBOL FOR CAI
  if {$char >= 127584 && $char <= 127589 } { return 2 }
  #  So    [33] CYCLONE..SHOOTING STAR
  if {$char >= 127744 && $char <= 127776 } { return 2 }
  #  So     [9] HOT DOG..CACTUS
  if {$char >= 127789 && $char <= 127797 } { return 2 }
  #  So    [70] TULIP..BABY BOTTLE
  if {$char >= 127799 && $char <= 127868 } { return 2 }
  #  So    [22] BOTTLE WITH POPPING CORK..GRADUATION CAP
  if {$char >= 127870 && $char <= 127891 } { return 2 }
  #  So    [43] CAROUSEL HORSE..SWIMMER
  if {$char >= 127904 && $char <= 127946 } { return 2 }
  #  So     [5] CRICKET BAT AND BALL..TABLE TENNIS PADDLE AND BALL
  if {$char >= 127951 && $char <= 127955 } { return 2 }
  #  So    [17] HOUSE BUILDING..EUROPEAN CASTLE
  if {$char >= 127968 && $char <= 127984 } { return 2 }
  #  So         WAVING BLACK FLAG
  if {$char == 127988} { return 2 }
  #  So     [3] BADMINTON RACQUET AND SHUTTLECOCK..AMPHORA
  if {$char >= 127992 && $char <= 127994 } { return 2 }
  #  Sk     [5] EMOJI MODIFIER FITZPATRICK TYPE-1-2..EMOJI MODIFIER FITZPATRICK TYPE-6
  if {$char >= 127995 && $char <= 127999 } { return 2 }
  #  So    [63] RAT..PAW PRINTS
  if {$char >= 128000 && $char <= 128062 } { return 2 }
  #  So         EYES
  if {$char == 128064} { return 2 }
  #  So   [187] EAR..VIDEOCASSETTE
  if {$char >= 128066 && $char <= 128252 } { return 2 }
  #  So    [63] PRAYER BEADS..DOWN-POINTING SMALL RED TRIANGLE
  if {$char >= 128255 && $char <= 128317 } { return 2 }
  #  So     [4] KAABA..MENORAH WITH NINE BRANCHES
  if {$char >= 128331 && $char <= 128334 } { return 2 }
  #  So    [24] CLOCK FACE ONE OCLOCK..CLOCK FACE TWELVE-THIRTY
  if {$char >= 128336 && $char <= 128359 } { return 2 }
  #  So         MAN DANCING
  if {$char == 128378} { return 2 }
  #  So     [2] REVERSED HAND WITH MIDDLE FINGER EXTENDED..RAISED HAND WITH PART BETWEEN MIDDLE AND RING FINGERS
  if {$char >= 128405 && $char <= 128406 } { return 2 }
  #  So         BLACK HEART
  if {$char == 128420} { return 2 }
  #  So     [5] MOUNT FUJI..MOYAI
  if {$char >= 128507 && $char <= 128511 } { return 2 }
  #  So    [80] GRINNING FACE..PERSON WITH FOLDED HANDS
  if {$char >= 128512 && $char <= 128591 } { return 2 }
  #  So    [70] ROCKET..LEFT LUGGAGE
  if {$char >= 128640 && $char <= 128709 } { return 2 }
  #  So         SLEEPING ACCOMMODATION
  if {$char == 128716} { return 2 }
  #  So     [3] PLACE OF WORSHIP..SHOPPING TROLLEY
  if {$char >= 128720 && $char <= 128722 } { return 2 }
  #  So     [2] AIRPLANE DEPARTURE..AIRPLANE ARRIVING
  if {$char >= 128747 && $char <= 128748 } { return 2 }
  #  So     [6] SCOOTER..SKATEBOARD
  if {$char >= 128756 && $char <= 128761 } { return 2 }
  #  So    [47] ZIPPER-MOUTH FACE..HANDBALL
  if {$char >= 129296 && $char <= 129342 } { return 2 }
  #  So    [49] WILTED FLOWER..SMILING FACE WITH SMILING EYES AND THREE HEARTS
  if {$char >= 129344 && $char <= 129392 } { return 2 }
  #  So     [4] FACE WITH PARTY HORN AND PARTY HAT..FREEZING FACE
  if {$char >= 129395 && $char <= 129398 } { return 2 }
  #  So         FACE WITH PLEADING EYES
  if {$char == 129402} { return 2 }
  #  So    [39] LAB COAT..SWAN
  if {$char >= 129404 && $char <= 129442 } { return 2 }
  #  So    [10] EMOJI COMPONENT RED HAIR..SUPERVILLAIN
  if {$char >= 129456 && $char <= 129465 } { return 2 }
  #  So     [3] CHEESE WEDGE..SALT SHAKER
  if {$char >= 129472 && $char <= 129474 } { return 2 }
  #  So    [48] FACE WITH MONOCLE..NAZAR AMULET
  if {$char >= 129488 && $char <= 129535 } { return 2 }
  #  Lo [42711] CJK UNIFIED IDEOGRAPH-20000..CJK UNIFIED IDEOGRAPH-2A6D6
  if {$char >= 131072 && $char <= 173782 } { return 2 }
  #  Cn    [41] <reserved-2A6D7>..<reserved-2A6FF>
  if {$char >= 173783 && $char <= 173823 } { return 2 }
  #  Lo  [4149] CJK UNIFIED IDEOGRAPH-2A700..CJK UNIFIED IDEOGRAPH-2B734
  if {$char >= 173824 && $char <= 177972 } { return 2 }
  #  Cn    [11] <reserved-2B735>..<reserved-2B73F>
  if {$char >= 177973 && $char <= 177983 } { return 2 }
  #  Lo   [222] CJK UNIFIED IDEOGRAPH-2B740..CJK UNIFIED IDEOGRAPH-2B81D
  if {$char >= 177984 && $char <= 178205 } { return 2 }
  #  Cn     [2] <reserved-2B81E>..<reserved-2B81F>
  if {$char >= 178206 && $char <= 178207 } { return 2 }
  #  Lo  [5762] CJK UNIFIED IDEOGRAPH-2B820..CJK UNIFIED IDEOGRAPH-2CEA1
  if {$char >= 178208 && $char <= 183969 } { return 2 }
  #  Cn    [14] <reserved-2CEA2>..<reserved-2CEAF>
  if {$char >= 183970 && $char <= 183983 } { return 2 }
  #  Lo  [7473] CJK UNIFIED IDEOGRAPH-2CEB0..CJK UNIFIED IDEOGRAPH-2EBE0
  if {$char >= 183984 && $char <= 191456 } { return 2 }
  #  Cn  [3103] <reserved-2EBE1>..<reserved-2F7FF>
  if {$char >= 191457 && $char <= 194559 } { return 2 }
  #  Lo   [542] CJK COMPATIBILITY IDEOGRAPH-2F800..CJK COMPATIBILITY IDEOGRAPH-2FA1D
  if {$char >= 194560 && $char <= 195101 } { return 2 }
  #  Cn     [2] <reserved-2FA1E>..<reserved-2FA1F>
  if {$char >= 195102 && $char <= 195103 } { return 2 }
  #  Cn  [1502] <reserved-2FA20>..<reserved-2FFFD>
  if {$char >= 195104 && $char <= 196605 } { return 2 }
  #  Cn [65534] <reserved-30000>..<reserved-3FFFD>
  if {$char >= 196608 && $char <= 262141 } { return 2 }
  return 1
}

proc ::textutil::wcswidth {string} {
  set width 0
  set len [string length $string]
  for {set i 0} {$i < $len} {incr i} {
    scan [string index $string $i] %c char
    set n [::textutil::wcswidth_char $char]
    if {$n < 0} {
      return -1
    }
    incr width $n
  }
  return $width
}

